commercelayer/app-elements

packages/app-elements/README.md
Closes #
I removed broken image url in reamde
=> Remove image in readme

packages/app-elements/src/ui/internals/InputWrapper.tsx, packages/app-elements/src/ui/resources/ResourceOrderSummary/AddCouponOverlay.tsx, packages/docs/src/mocks/data/orders.js
Show a message when the coupon cannot be added (e.g. coupon doesn't exist).
https://deploy-preview-402--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourceordersummary--docs#without-a-coupon-code
=> Handle error messages when adding a coupon in the order summary

packages/app-elements/src/ui/atoms/Alert.tsx, packages/app-elements/src/ui/composite/ListItem.tsx, packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx, packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap, packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx, packages/app-elements/src/ui/resources/ResourceOrderSummary/utils.tsx, packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
Add `paddingSize` to the `<ListItem>` component
=> Add `paddingSize` to the `<ListItem>` component

packages/app-elements/package.json, packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx, pnpm-lock.yaml
I updated the SDK library package to latest version (`5.21.1`) in order to avoid the unwanted mandatory nature of some attributes of `line_items` resource, introduced by a previously updated version of the SDK package itself.
=> Update SDK package to fix unwanted behaviors

packages/app-elements/src/ui/atoms/Icon/icons.tsx
I've added two icons:
- GitHub 
- Google
=> Add GitHub and Google icons

packages/app-elements/tailwind.config.cjs
I've added a new breakpoint so we can have our main `<Container>` growing up to a width of `630px` for md viewport.
=> Add new breakpoint for container

packages/app-elements/src/main.ts, packages/app-elements/src/ui/atoms/ScrollToTop.tsx, packages/app-elements/src/ui/composite/PageLayout.tsx
Added `ScrollToTop` component to manage a scroll to top effect driven by the `window.location.pathname`
Added a new prop `scrollToTop` to manage scroll to top behavior directly in `PageLayout`
=> Add `ScrollToTop` component and `PageLayout` behavior

packages/app-elements/src/ui/atoms/Grid.tsx, packages/docs/src/stories/atoms/Grid.stories.tsx
I've fixed the default grid alignment as undefined and improved its documentation.
=> Adjust grid alignment and responsiveness

packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Added `shipments.stock_transfers` support to `ResourceOrderTimeline`.
The feature will cover the show of completed stock transfers inside the order timeline (currently used by both `orders` and `shipments` apps). Each stock transfer will be linked to its detail page (inside stock_transfers app) according to current user accessibility permissions.
=> Add `shipments.stock_transfers` support to `ResourceOrderTimeline`

packages/app-elements/src/ui/atoms/ButtonImageSelect.tsx
- Fixed typings of `ButtonImageSelect` component
- Fixed border color of  `ButtonImageSelect` component
=> Fix typings of `ButtonImageSelect` component

packages/app-elements/src/ui/atoms/Icon/icons.tsx
Added `LockSimple` Phosphor icon
=> Add `LockSimple` Phosphor icon

packages/app-elements/src/ui/atoms/Spacer.tsx
Added value `1` to `Spacer` component
=> Add value `1` to `Spacer` component

packages/app-elements/src/providers/TokenProvider/getAccessTokenFromUrl.ts, packages/app-elements/src/providers/TokenProvider/storage.ts, packages/app-elements/src/providers/TokenProvider/url.ts, packages/app-elements/vite.config.ts
`app-elements` can now run on Next.js
=> `app-elements` can run on Next.js

packages/docs/src/stories/utility/Currency.stories.tsx
I added the documentation for the currency helpers
https://deploy-preview-529--commercelayer-app-elements.netlify.app/?path=/docs/utility-currency--docs
=> Add documentation for currency helpers

packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
Hided `Dropdown` if no items are set
=> Hide `Dropdown` if no items are set

packages/app-elements/src/ui/atoms/Stack.tsx
Closes commercelayer/issues-app#21
Reworked the `Stack` component to resolve reported/known issues:
- Improve children spacings
- Remove unwanted side padding
- Add `mobile` vertical behavior
=> Improve `Stack` spacings and add `mobile` vertical behavior

packages/app-elements/src/ui/atoms/Icon/icons.tsx
Added support for Phosphor `Trash` icon
=> Add `trash` icon support

packages/app-elements/src/ui/atoms/Icon/icons.tsx
I've added 2 new icons:
- clipboardText
- webhookLogo
=> Add clipboardText and webhookLogo icons

packages/app-elements/src/providers/TokenProvider/types.ts
`resources` is now an allowed app
=> Add `resources` to `TokenProviderAllowedApp`

packages/app-elements/src/ui/forms/InputDate/InputDateComponent.css, packages/docs/src/stories/forms/ui/InputDate.stories.tsx
=> Input date time will never break into two lines

packages/app-elements/src/ui/atoms/Button.test.tsx, packages/app-elements/src/ui/atoms/Button.tsx, packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Added optional `flex` alignment to `Button` component
=> Add optional `flex` alignment to `Button` component

packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
I updated the `InputRadioGroup` ui
=> Update `InputRadioGroup` ui

packages/app-elements/src/ui/resources/ResourceList/metricsApiClient.ts
I've added a new condition to check if `ResourceList` is fetching pending orders from the metrics API.
In that case, the endpoint to be called is `/cart` instead of `/orders`
=> Use metrics API `carts` endpoint when fetching pending orders

packages/app-elements/src/hooks/useEditMetadataOverlay.tsx, packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
Enforced metadata show and fix updated payload
=> Enforce metadata show and fix updated payload

packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx, packages/app-elements/src/ui/resources/ResourceMetadata/utils.test.ts, packages/app-elements/src/ui/resources/ResourceMetadata/utils.ts, packages/docs/src/mocks/data/customers.js
Avoid duplicate keys when editing metadata.
https://deploy-preview-617--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcemetadata--docs
Add `first_name` or `age`.
=> Avoid duplicate keys when editing metadata

packages/app-elements/src/ui/atoms/Icon/icons.tsx
=> Add `clockClockwise` icon

packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
Closes #
Updated action UI of `ResourceMetadata` component
=> Update action UI of `ResourceMetadata` component

packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx, packages/app-elements/tailwind.config.cjs
=> Update checkbox style

packages/app-elements/src/ui/composite/PageSkeleton.tsx
I've set `scrollToTop` in `PageSkeleton`
=> Set scrollToTop in `PageSkeleton`

packages/app-elements/src/ui/atoms/Icon/icons.tsx
I've added the `envelopeSimple` icon
=> Add `envelopeSimple` icon

packages/app-elements/src/ui/resources/ResourceList/metricsApiClient.ts
When fetching carts (pending orders) with metrics API, we will also get orders that have been placed. This is the way the metrics API `/carts` endpoint works and is intended to be used.
The result is that we get a list of pending orders that actually might have been placed.
This PR fixes this behavior by calling `/orders` endpoint every time the carts are fetched to find out if those orders have been placed at some point.
=> Filter out placed orders when fetching carts with metrics-api

packages/app-elements/src/ui/composite/Timeline.tsx
I added seconds to the timeline time.
=> Add seconds to the timeline

packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
Now, when using the InputSelect component, an option can have a boolean value.
=> Allow boolean in InputSelectValue

packages/app-elements/src/ui/atoms/Badge/Badge.tsx, packages/app-elements/src/ui/atoms/Badge/badgeVariants.ts, packages/app-elements/src/ui/atoms/PageHeading/PageHeading.test.tsx, packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
I've updated the badge variants to match the latest design.
https://deploy-preview-695--commercelayer-app-elements.netlify.app/?path=/docs/atoms-badge--docs#available%20variants
=> Update badge colors for non-solid variant

packages/app-elements/src/ui/atoms/Icon/icons.tsx
Added `archive` and `shoppingBagOpen` icons
=> Add `archive` and `shoppingBagOpen` icons

packages/app-elements/src/ui/atoms/Badge/badgeVariants.ts
I've updated colors for badges with variant secondary-solid and teal-solid
=> Update style for badge solid variants

packages/app-elements/src/ui/atoms/Icon/icons.tsx
I've added `arrowCircleUpRight` icon
=> Add `arrowCircleUpRight` icon

packages/app-elements/src/ui/atoms/Icon/icons.tsx
Added `shareFat` and `whatsappLogo` icons
=> Add `shareFat` and `whatsappLogo` icons

packages/app-elements/src/ui/atoms/Icon/icons.tsx
I've added a new `flashlight` icon
=> Add `flashlight` icon

packages/app-elements/src/ui/forms/InputSelect/GenericAsyncComponent.tsx
I improved the UX for the `AsyncCreatableSelect` component.
https://github.com/user-attachments/assets/4ad6d063-d586-40a1-80cf-ac1742bc4722
=> Improve UX for the `AsyncCreatableSelect` component

packages/app-elements/src/ui/atoms/Icon/icons.tsx
=> Add `Copy` icon

packages/app-elements/src/main.ts, packages/app-elements/src/mocks/data/markets.ts, packages/app-elements/src/mocks/handlers.ts, packages/app-elements/src/ui/forms/MarketWithCurrencySelector/HookedMarketWithCurrencySelector.test.tsx, packages/app-elements/src/ui/forms/MarketWithCurrencySelector/HookedMarketWithCurrencySelector.tsx, packages/app-elements/src/ui/forms/MarketWithCurrencySelector/index.tsx, packages/docs/src/stories/forms/react-hook-form/HookedMarketWithCurrencySelector.stories.tsx
https://deploy-preview-735--commercelayer-app-elements.netlify.app/?path=/docs/forms-react-hook-form-hookedmarketwithcurrencyselector--docs
This pull request introduces a new component designed for use within a React Hook Form context. The component features two key functionalities:
1. **Market Selection**: A dropdown to choose a market with data fetched from the API. This select includes an autocomplete feature for easy searching.
1. **Currency Selection**: A conditional dropdown for selecting a currency, which is hidden if the selected market already specifies a currency in its price list.
* **Dynamic Currency Selection**: If a market is selected, the currency input is hidden, and the currency is automatically set to the one associated with the selected market’s price list.
* **Default …
=>  add `HookedMarketWithCurrencySelector` component

packages/app-elements/src/styles/vendor.css, packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/app-elements/src/ui/internals/InteractiveElement.className.ts, packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap, packages/app-elements/tailwind.config.cjs, packages/docs/src/stories/getting-started/001.welcome.mdx
I updated primary color setup in Tailwind config according to our design palette.
This should update any element relying on primary color, link links, and other basic elements.
=> Update primary color setup in TW config

packages/app-elements/src/styles/vendor.css, packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx, packages/app-elements/src/ui/internals/InteractiveElement.className.ts
Enforced underline behavior of links to be restricted to simple links.
=> Enforce `underline` behavior of links

packages/app-elements/src/ui/atoms/Icon/icons.tsx
I added the new `QrCode` icon.
=> Add `QrCode` icon

packages/app-elements/src/hooks/useEditMetadataOverlay.tsx, packages/app-elements/src/hooks/useEditTagsOverlay.tsx, packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx, packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx, packages/app-elements/src/ui/resources/ResourceTags.tsx, packages/docs/src/stories/resources/ResourceMetadata.stories.tsx, packages/docs/src/stories/resources/ResourceTags.stories.tsx
- Improved empty list cases and docs of `ResourceMetadata` and `ResourceTags` components
- Added seconds in `ResourceDetails` dates
- Show empty `origin` and `origin_name` attributes in `ResourceDetails`
- Added missing `pencil` icon in `metadata` `Edit` button
- Replaced `Back` actions of `metadata` and `tags` overlays with `Close` / `x` action
=> Improve `Resource`s  components

packages/app-elements/src/ui/resources/ResourceTags.tsx
=> Fix behavior of empty tags

packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
Shown year in `ResourceDetails` component.
=> Show year in `ResourceDetails` component

packages/app-elements/src/helpers/date.ts, packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
Refined `ResourceDetails` component and `date` helper
=> Refine `ResourceDetails` and `date` helper

packages/app-elements/src/ui/atoms/Icon/icons.tsx
=> Add `arrowsDownUp` icon

packages/app-elements/src/hooks/useEditMetadataOverlay.tsx, packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Fixed repaints of `ResourceMetadata` form
=> Fix repaints of `ResourceMetadata` form

packages/app-elements/src/ui/atoms/Section.tsx, packages/docs/src/stories/atoms/Section.stories.tsx
Enhance `Section` component to support multiple actions passed inside `actionButton` prop inside a `React.Fragment` like this to avoid braking changes:
`<><Button /><Button /></>`
=> Enhance `Section` component to support multiple actions via `actionButton` prop

packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Fixed `ResourceMetadata` component to use the right processed `metadata` object from form to patch the wanted resource
=> Fix form payload of `ResourceMetadata` component

packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx, packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Enforce `ResourceMetadata` overlay form to avoid unwanted repaints.
=> Enforce `ResourceMetadata` overlay

packages/app-elements/src/ui/forms/InputSelect/HookedInputSelect.tsx, packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx, packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx, packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx, packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx, packages/app-elements/src/ui/resources/ResourceAddress/useResourceAddressOverlay.tsx, packages/docs/src/mocks/data/addresses.js, packages/docs/src/stories/resources/ResourceAddress.stories.tsx
I added the ability to add a new address from the `ResourceAddress` component.
=> Ability to add a new address from the `ResourceAddress` component

packages/app-elements/src/dictionaries/promotions.ts, packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts, packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx, packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx, packages/app-elements/src/ui/resources/ResourceListItem/types.ts, packages/docs/src/stories/resources/ResourceListItem.stories.tsx
I added support for `FlexPromotions` in the `ResourceListItem` component.
=> Manage FlexPromotions in the ResourceListItem component

packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx, packages/app-elements/src/ui/forms/CodeEditor/HookedCodeEditor.tsx
I fixed how the `CodeEditor` handle onChange event.
=> CodeEditor better manages onChange event

packages/app-elements/src/ui/atoms/Icon/icons.tsx
I have added a new `arrowUp` icon
=> Add arrowUp icon

packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.test.ts
I have added `order.store` relationship to `fechCoreResourceSuggestion` snapshop
=> Update `CodeEditor` test snapshot to include new resource

packages/app-elements/src/ui/atoms/Icon/icons.tsx
=> Add new `key` icon

packages/app-elements/src/ui/atoms/Icon/icons.tsx
=> Add new discord icon

packages/app-elements/src/hooks/useEditTagsOverlay.tsx
Read tags limit from feature flag.
=> Read tags limit from feature flag

packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts, packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
According to commercelayer/issues-app/issues/298 the shipment list item should show shipping method name instead of stock location.
=> Enhance shipment list item

packages/app-elements/src/ui/internals/InteractiveElement.className.ts
I increased the height when button uses the input variant
=> Increase height when button uses the input variant

packages/app-elements/src/main.ts, packages/app-elements/src/ui/composite/Address.tsx, packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx, packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx, packages/docs/src/stories/composite/Address.stories.tsx
I extracted the `Address` component from the `ResourceAddress` component.
https://deploy-preview-875--commercelayer-app-elements.netlify.app/?path=/docs/composite-address--docs
=> Extract the `Address` component from the `ResourceAddress` component

packages/app-elements/src/ui/atoms/Icon/icons.tsx
=> Add `wrench` icon

packages/app-elements/package.json, packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx, packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx, pnpm-lock.yaml
I removed the shared `shouldRender` methods from main context
=> Removed unused shouldRender method

packages/app-elements/tailwind.config.cjs
According to design team I increase xl tailwind breakpoint from 1200px to 1280px.
=> Increase xl tailwind breakpoint

packages/app-elements/src/ui/forms/Form/HookedForm.tsx
I added `preventDefault` and `stopPropagation` to the `HookedForm`.
=> Add `preventDefault` and `stopPropagation` to the `HookedForm`

packages/app-elements/src/locales/en.ts, packages/app-elements/src/locales/it.ts, packages/app-elements/src/main.ts, packages/app-elements/src/ui/resources/ResourceAttachments/ResourceAttachments.tsx, packages/app-elements/src/ui/resources/ResourceAttachments/index.tsx, packages/docs/src/mocks/data/orders.js, packages/docs/src/stories/resources/ResourceAttachments.stories.tsx
Added `ResourceAttachments` component to show attachment with an URL.
=> Add attachments component

packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
Refine UI of `ResourceMetadata` component by removing side gutter in metadata list.
=> Refine UI of `ResourceMetadata` component

.ncurc.js, packages/app-elements/package.json
I update `peerDependencies` to the latest major.
=> Update peerDependencies to the latest major

packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts, packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
Read `image_url` and `name` directly from the `stock_line_item`.
=> Read `image_url` and `name` directly from the `stock_line_item`

packages/app-elements/src/ui/forms/Input/Input.tsx
I added and managed the type `hidden` to the input.
=> Add `type="hidden"` to the Input and HookedInput components

packages/app-elements/src/ui/forms/InputSwitch/InputSwitch.tsx
Refined the UI of `InputSwitch` component according to updated design.
The updated design is same as the one used for the Test mode switch inside the top bar.
=> Refine ui of `InputSwitch` component

packages/app-elements/src/ui/atoms/Icon/icons.tsx
=> Add `gear` icon

packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
Increased top margin of searchbar according to updated design requirements.
=> Increase top margin of SearchBar

packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
Enforced types of `SkeletonTemplate` component.
=> Enforce types of `SkeletonTemplate`

packages/app-elements/src/hooks/useEditTagsOverlay.tsx
Align the set of options used to list tags of a resource in list component and in form component of `ResourceTags` component.
Thanks to this fix the list component is updated along with the form component after the tags relationship is patched.
=> Fix updated tags mutation 

packages/app-elements/src/locales/en.ts, packages/app-elements/src/locales/it.ts
Added translation variable for coupon code min length.
=> Add translation for coupon code min length

packages/app-elements/src/locales/en.ts, packages/app-elements/src/locales/it.ts
Added translations for customer anonymization.
=> Add translations for customer anonymization

packages/app-elements/src/locales/en.ts, packages/app-elements/src/locales/it.ts, packages/app-elements/src/ui/resources/ResourcePaymentMethod.tsx
Added card expiry information to `ResourcePaymentMethod` component.
The optional `Show more` row is now moved to a dedicated row in the layout according to updated design.
=> Add card expiry information to `ResourcePaymentMethod` component

packages/app-elements/src/helpers/giftCards.test.ts, packages/app-elements/src/helpers/giftCards.ts, packages/app-elements/src/main.ts, packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts, packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
=> Show masked gift card code in `ResourceLineItems`

packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts, packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
Closes #
Show reference in ResourceListItem > shipment, if present
=> Show reference in ResourceListItem > shipment

packages/app-elements/src/ui/forms/InputSelect/overrides.tsx, packages/app-elements/src/ui/forms/InputSelect/styles.ts
Closes commercelayer/issues-app#401
Updates some InputSelect css to match new design
https://deploy-preview-954--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputselect--docs
=> Update `InputSelect` css

packages/app-elements/src/ui/forms/RuleEngine/Action/ActionListItem.tsx, packages/app-elements/src/ui/forms/RuleEngine/Action/ActionValue.tsx, packages/app-elements/src/ui/forms/RuleEngine/Condition/ConditionListItem.tsx, packages/app-elements/src/ui/forms/RuleEngine/Condition/ConditionMatcher.tsx, packages/app-elements/src/ui/forms/RuleEngine/Condition/ConditionValue.tsx, packages/app-elements/src/ui/forms/RuleEngine/RuleEngineComponent.tsx, packages/app-elements/src/ui/forms/RuleEngine/__snapshots__/index.test.tsx.snap, packages/app-elements/src/ui/forms/RuleEngine/index.test.tsx
I added more tests to the `RuleEngine` component.
=> Add more tests to the RuleEngine component

packages/app-elements/src/mocks/setup.ts, packages/app-elements/src/styles/global.css, packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx, packages/app-elements/src/ui/forms/RuleEngine/Action/ActionListItem.tsx, packages/app-elements/src/ui/forms/RuleEngine/RuleEngineComponent.tsx, packages/app-elements/src/ui/forms/RuleEngine/RuleEngineContext.tsx, packages/app-elements/src/ui/forms/RuleEngine/index.test.tsx, packages/app-elements/src/ui/forms/RuleEngine/utils.ts, packages/docs/src/stories/forms/react-hook-form/HookedCodeEditor.stories.tsx, packages/docs/src/stories/forms/ui/CodeEditor.stories.tsx, packages/docs/src/stories/forms/ui/RuleEngine.stories.tsx
I added the ability to manage price rules to the `RuleEngine` component.
https://deploy-preview-982--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-ruleengine--docs#price-rules
=> Rule engine for price rules

packages/app-elements/src/ui/internals/Overlay.tsx
I've set a max width to the overlay drawer and fixed z-index of its backdrop
=> Tune overlay drawer css

packages/app-elements/src/ui/forms/RuleEngine/RuleEngineContext.tsx, packages/docs/src/stories/forms/ui/RuleEngine.stories.tsx
I started using the deep clone when setting a path.
=> Use deep clone when setting a path

packages/app-elements/src/main.ts
Added a missing type to the export list
=> Add SkeletonTemplateProps type export
