- packages/docs/src/generate-abilities.mjs
I've added a special check for the `organizazion` resource that is referenced in core API documentation as singular, but arrives from the yaml as plural.
This was resulting in broken URL:
`.../api-reference/organizations/object` instead of `.../api-reference/organization/object`
Before
Now
https://deploy-preview-387--commercelayer-app-elements.netlify.app/?path=/docs/getting-started-applications--docs
> Handle special case for `organization` resource on abilities page

- packages/app-elements/src/ui/resources/ResourceListItem/transformers/returns.tsx
I updated the generation of the `name` prop of `ResourceListItem` of resource type `returns` by enforcing some checks about possible `null` / `undefined` parts of the string and adding a prefix according to design decisions.
> Enforce and update `ResourceListItem` `returns` name

- packages/app-elements/src/ui/forms/InputCheckboxGroup.test.tsx
- packages/app-elements/src/ui/forms/InputCheckboxGroup.tsx
Since `InputCheckbox` prevents click propagation, I've fixed a behaviour where click on inner checkbox was not working in `InputCheckboxGroup`
In current (at the time of writing) version clicking on checkbox is not working (you must click on the entire item)
https://commercelayer.github.io/app-elements/?path=/docs/forms-ui-inputcheckboxgroup--docs
With the fix, you can also click on the inner checkbox
https://deploy-preview-392--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputcheckboxgroup--docs
> Allow to interact with inner checkbox in `InputCheckboxGroup`

- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/types.ts
I enforced `ResourceListItem` component to provide a complete management of the behavior of its right side. Right side of the `ResourceListItem` could be: empty, a right arrow in case of linkable list item or a custom right content defined per resource in each transformer helper when needed.
First of all I set the right arrow to be shown if the `onClick` prop is defined. In the same condition also the `ListItem` `tag` prop is set to `a` in the same case.
Then I added a new prop called `showRightContent` to let the component to show the custom right content instead of right arrow when needed and controlled by app.
> Enforce `ResourceListItem` right column management

- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
I added a conditional check to verify that at least one reason is provided in `return_reason` object before to render the block.
> Show return `reason` in ResourceLineItem only if filled

- packages/app-elements/src/ui/atoms/Tag.tsx
- packages/app-elements/src/ui/composite/ListItem.tsx
- packages/app-elements/src/ui/resources/ResourceTags.tsx
- packages/app-elements/src/utils/htmltags.test.ts
- packages/app-elements/src/utils/htmltags.ts
- Fixed hooks order in `ResourceTags` component
- Remove unwanted props in `Tag` and `ListItem` components
> Fix hooks order in `ResourceTags` and remove unwanted props in `Tag` and `ListItem`

- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/atoms/Alert.test.tsx
- packages/app-elements/src/ui/atoms/Alert.tsx
- packages/docs/src/stories/atoms/Alert.stories.tsx
I added a brand new `<Alert>` component. Alerts are visual representations used to communicate a state that affects the page or the interactive element.
https://deploy-preview-397--commercelayer-app-elements.netlify.app/?path=/docs/atoms-alert--docs
> Add new `<Alert>` component

- packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
- packages/app-elements/src/ui/composite/Timeline.tsx
- packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.test.tsx
- packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx
- packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
I managed the permissions of the OrderSummary and OrderTimeline components. Now when the connected users have only view permissions, they will not see any action to update/create/delete resources:
- In the OrderSummary they will not be able to edit the order.
- In the OrderTimeline they will not be able to add comments.
> Remove create/update/delete abilities for users with read-only permission on OrderSummary and OrderTimeline

- packages/app-elements/src/dictionaries/orders.ts
I fixed a few cases where the order status was not handled:
- `placed:partially_refunded:unfulfilled`
- `approved:partially_refunded:not_required`
- `cancelled:refunded:not_required`
- `cancelled:unpaid:unfulfilled`
- `cancelled:free:unfulfilled`
> Handle more order statuses

- packages/app-elements/src/dictionaries/orders.ts
I fixed a few cases where the order status was not handled:
- `placed:paid:not_required`
- `placed:partially_refunded:not_required`
> Handle missing order statuses

- packages/app-elements/src/ui/forms/InputSelect/styles.ts
- packages/app-elements/src/ui/internals/InputWrapper.tsx
The `InputSelect` style did not match the same as other inputs.
This PR solves this by setting outlines using box-shadow instead of borders.
Before: 
Now:
> Uniform `<InputSelect>` style as other inputs

- packages/app-elements/package.json
- packages/app-elements/src/main.ts
- packages/app-elements/src/providers/GTMProvider.test.tsx
- packages/app-elements/src/providers/GTMProvider.tsx
- pnpm-lock.yaml
Added `GTMProvider` to introduce a straightforward Google Tag Manager implementation for our apps by using `react-gtm-module` with a provided `gtmId`.
Usage of the provider should be something like this:
```JSX
<GTMProvider gtmId='ABC-1234567'>
<div>App</div>
</GTMProvider>
```
> Add `GTMProvider`

- packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
Since `InputRadioGroup` is enhanced with SkeletonTemplate, we need to export the full interface or the `isLoading` prop was not available.
> Add missing `isLoading` prop to `InputRadioGroupProps`

- packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
I added `order` `returns` status changes in `ResourceOrderTimeline` component.
> Add `returns` in `ResourceOrderTimeline` component

- packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
As all the others `HookedInput...` components, feedback to show validation error is controlled internally.
> Add missing `feedback` to` HookedInputCheckbox`

- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
- I modified the `Restocked on` badge of `ResourceLineItem` component to show `Restocked today` if formatted date is `Today` or otherwise `Restocked on {date}`.
> Fix phrase in `Restocked on` badge of `ResourceLineItem` component

- packages/app-elements/src/ui/atoms/Alert.tsx
- packages/app-elements/src/ui/atoms/Card.test.tsx
- packages/app-elements/src/ui/atoms/Card.tsx
- packages/app-elements/src/ui/composite/CardDialog.tsx
- packages/app-elements/src/ui/composite/Timeline.tsx
- packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroup.tsx
- packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
- packages/app-elements/src/ui/forms/InputResourceGroup/FullList.tsx
- packages/app-elements/src/ui/forms/InputResourceGroup/InputResourceGroup.tsx
- packages/docs/src/stories/atoms/Card.stories.tsx
- packages/docs/src/stories/examples/FiltersCheckboxes.stories.tsx
In order to apply the pattern from the screenshots attached I've added:
- optional `backgroundColor` prop that can be set to `light`
- mandatory `overflow` prop that can allow inner content to overflow or not the card. Before overflow was always hidden since it was required when card was used to group list items with hover effect.
- update all components that use `<Card>` to set proper overflow value
As you can see, the dropdown menu of the select needs to overflow the card boundaries.
[Preview link](https://deploy-preview-421--commercelayer-app-elements.netlify.app/?path=/docs/atoms-card--docs#with-overflowing-content)
The new prop `overflow` is required, so at the next update consumer apps that use `<Card>` need to specify the wanted behavior.
> Add optional background color to Card and allow overflowing content

- packages/app-elements/src/ui/atoms/Hr.tsx
- packages/app-elements/src/ui/resources/ResourceShipmentParcels.mocks.tsx
- packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
- packages/docs/src/stories/atoms/Hr.stories.tsx
- packages/docs/src/stories/resources/ResourceShipmentParcels.stories.tsx
I've enabled the showing of customs info in the parcel box (when available)
https://deploy-preview-417--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourceshipmentparcels--docs
> Add parcel customs info

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
- packages/app-elements/src/main.ts
I added a new `date` helper method called `formatDateWithPredicate`, extending existing `formatDate` method, to generate a nice string like `Created on Jul 21, 2022 · 1:16 PM`.
It expects the same props found in `formatDate` method with in addition the `predicate` string (eg. 'Created').
It generates a string starting from the `predicate`, followed by the proper separator for the chosen format and the formatted date itself.
> Add `formatDateWithPredicate` date helper method

- packages/app-elements/src/ui/forms/InputCurrency/InputCurrency.test.tsx
- packages/app-elements/src/ui/forms/InputCurrency/InputCurrency.tsx
- packages/app-elements/src/ui/forms/InputCurrency/utils.ts
- packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
- packages/docs/src/mocks/data/adjustments.js
- packages/docs/src/mocks/data/line_items.js
- packages/docs/src/stories/forms/ui/InputCurrency.stories.tsx
- packages/docs/src/stories/resources/ResourceOrderSummary.stories.tsx
The `<InputCurrency>` component now have a `sign` prop that accepts `'+' | '-' | '+-' | '-+'`. This defines which are the available signs:
- `+` can accepts only positive numbers.
- `-` can accepts only negative numbers.
- `+-` can accepts both positive and negative numbers, with the default to positive.
- `-+` can accepts both positive and negative numbers, with the default to negative.
----
In the `<ResourceOrderSummary>` the adjustment can be set to a positive or a negative value (default to negative).
https://deploy-preview-403--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputcurrency--docs
https://deploy-preview-403--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourceordersummary--docs#without-a-manual-adjustment
> `<InputCurrency>` can define which are the available `sign`s

- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/atoms/RemoveButton.test.tsx
- packages/app-elements/src/ui/atoms/RemoveButton.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
- packages/app-elements/src/ui/resources/ResourceOrderSummary/DeleteCouponButton.tsx
- packages/docs/src/stories/atoms/RemoveButton.stories.tsx
Add a new `RemoveButton` component. This component is used within the app-elements but can also be used in all the applications.
> Add RemoveButton component

- packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
I modified `ResourceOrderTimeline` component by adding `order.returns` to be included in component SDK request to show `returns` related statuses.
> Add missing include in `ResourceOrderTimeline` to enable `returns` statuses

- packages/app-elements/src/ui/resources/ResourceListItem/transformers/returns.tsx
Closes #
I modified the `ResourceListItem` component to use as destination the `return.stock_location` instead of `order.market`
> Use `return.stock_location` instead of `order.market`

- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
I've added `notes` to the address form schema, without it that field was not passed to the address PATCH request.
(by default zod removes all data not defined in the schema, so `notes` was not available in the `onSubmit` callback)
> Add missing `notes` field to address form schema

- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
Add missing `displayName` on the `ResourceAddress` component
> Add missing `displayName` on the `ResourceAddress` component

- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
I added a `useEffect` hook to update `address` internal state  of `ResourceAddress` component every time component `resource` prop value is changed.
> Add missing `useEffect` for `ResourceAddress` internal state

- packages/app-elements/src/dictionaries/shipments.ts
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/index.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/types.ts
- packages/docs/src/stories/resources/ResourceListItem.stories.tsx
- I added new `shipments` type to `ResourceLineItem` component.
- The new type is already compatible with `shipments.stock_transfers` relationship.
> Add `shipments` type to `ResourceLineItem` component

- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/types.ts
- packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
I modified `ResourceLineItems` component to support an optional custom attribute `stockTransfer` for items of type `stock_line_item. This attribute expects to be filled with a `StockTransfer` SDK object in order to show below the `stock_line_item` item informations about its related stock transfer.
> Add optional `stock transfer` visualization in `ResourceLineItems` component

- packages/app-elements/package.json
- packages/app-elements/src/mocks/data/countries.ts
- packages/app-elements/src/mocks/handlers.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
- pnpm-lock.yaml
I've removed the`@ac-dev/countries-service`  package that was used to generate a list of countries for the address form select options (`ResourceAddress` component).
Now we dynamically fetch countries and states from cdn (just IT and US for now) and populate the select according.
https://github.com/commercelayer/app-elements/assets/30926550/3ae12dce-552d-4f28-9d2c-1242ba2cbb57
> Replace `@ac-dev/countries-service` in ResourceAddress with static list of countries and states from cdn

- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/composite/SwitchMode.test.tsx
- packages/app-elements/src/ui/composite/SwitchMode.tsx
- packages/docs/src/stories/composite/SwitchMode.stories.tsx
I've added a custom switch component to be used to show the current mode (test or live) and to change it.
https://deploy-preview-449--commercelayer-app-elements.netlify.app/?path=/docs/composite-switchmode--docs
> Add `<SwitchMode>` component

- packages/app-elements/src/ui/resources/ResourceTags.tsx
I added `shipments` to the taggable resource types of `ResourceTags` component in order to let it to be used also for this kind of resource type in our apps.
> Add `shipments` support to `ResourceTags` component

- packages/app-elements/src/ui/atoms/Icon/icons.tsx
I added `Pulse` phosphor icon. It will be used to represent the concept of something that is running with the need of using an icon different from the mostly used `Check` icon.
> Add `Pulse` icon

- packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
I modified the `ResourceListItem` component to consider only `stock_transfers` with a `status` not in `completed`, `cancelled` and `draft`
> Restrict `ResourceListItem` usage of `stock_transfers` to some defined statuses

- packages/app-elements/src/ui/atoms/Badge/Badge.test.tsx
- packages/app-elements/src/ui/atoms/Badge/Badge.tsx
- packages/app-elements/src/ui/atoms/Icon/icons.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
- packages/docs/src/stories/atoms/Badge.stories.tsx
I modified the `Badge` component to let it show a little bold icon, on the left side of its content, based on a new optional `icon` prop. The `icon` prop will expects to be filled with one of our preselected icons name.
Icon size and weight props will be managed internally by the `Badge`.
> Add `icon` to `Badge` component

- packages/app-elements/src/ui/composite/OrganizationMenu.tsx
Border radius in Organization menu was wrong, since it was set only on the right `-r`.
I've fixed that
> Set correct border radius in `OrganizationMenu`

- packages/app-elements/src/ui/atoms/Icon/icons.tsx
- packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownDivider.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
- packages/docs/src/stories/composite/Dropdown.stories.tsx
- Improve the usage of the `icon` prop on `DropdownItem`, so it can consume directly the `<Icon>` component
- Add `header` to `DropdownMenu`
- Align spacings to the latest design
- Set a max width for the menu (250px + ellipsis for content)
https://deploy-preview-462--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#menu-with-header
Example:
When header or item label is too long it will be ellipsed, html `title` attribute will provide native tooltip
> Add header and icons in `Dropdown`

- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/composite/Dropdown/DropdownSearch.test.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownSearch.tsx
- packages/app-elements/src/ui/composite/Dropdown/index.ts
- packages/docs/src/stories/composite/Dropdown.stories.tsx
I've added a new component `DropdownSearch` to be used inside the dropdown menu to render an input.
The searched value is debounced by default.
In the future, we might discover that the search pattern is consistent everywhere so we will want to export instead a component that also returns a filtered list, but at the moment let's keep this modular by placing the search input and manually rendering a list of DropdownItem underneath.
https://deploy-preview-463--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#with-dropdown-search
Example:
```tsx
<Dropdown
dropdownItems={
<>
<DropdownSearch
onSearch={(hint) => {
console.log(hint)
}}
placeholder='Search...'
/>
<DropdownDivider />
{filteredData.map((item) => (
<DropdownItem key={item.key} label={item.label} />
))}
</> …
```
> Add DropdownSearch component

- packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx
- packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/docs/src/stories/composite/Dropdown.stories.tsx
`Dropdown` can now be opened in different positions (relative to the trigger button):
- top-left
- top-right
- bottom-right
- bottom-left
Plus, the dropdown arrow is now automatically centered on the base of a maximum 50px button.
This means that if the trigger button is smaller than 50px the arrow will be centered, otherwise will be aligned to the menu position
https://deploy-preview-464--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#positioning
> Add Dropdown menu position

- packages/app-elements/src/hooks/useOverlay.tsx
- packages/docs/src/stories/hooks/useOverlay.stories.tsx
I've added a new background option to open the `Overlay` with a light gray background
https://deploy-preview-466--commercelayer-app-elements.netlify.app/?path=/docs/hooks-useoverlay--docs#overlay-with-background-variant
> Add light background variant to `Overlay` component

- packages/app-elements/src/ui/atoms/Icon/Icon.tsx
- packages/app-elements/src/ui/atoms/Icon/icons.tsx
I've added new icons: 
- appWindow
- globe
- puzzle
and replace Icon props from phosphor with a custom subset.
In this way, the consumer app does not need to include phosphor package just to use proper typings
> Add new icons

- packages/app-elements/src/ui/atoms/PageHeading.test.tsx
- packages/app-elements/src/ui/atoms/PageHeading.tsx
- packages/app-elements/src/ui/composite/PageError.tsx
- packages/app-elements/src/ui/composite/PageLayout.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
- packages/app-elements/src/ui/resources/ResourceOrderSummary/AddCouponOverlay.tsx
- packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
- packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
- packages/app-elements/src/ui/resources/ResourceTags.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FieldTimeRange.tsx
- packages/docs/src/stories/atoms/PageHeading.stories.tsx
- packages/docs/src/stories/composite/PageLayout.stories.tsx
- packages/docs/src/stories/examples/FiltersCheckboxes.stories.tsx
- packages/docs/src/stories/examples/ListImports.stories.tsx
- packages/docs/src/stories/examples/ListResources.stories.tsx
- packages/docs/src/stories/examples/ListSkus.stories.tsx
I've replaced `onGoBack` prop with `navigationButton` that requires the following:
```ts
navigationButton?: {
/* Button label */
label: string
/* Button callback */
onClick: () => void
/**
* Button icon
* @default arrowLeft
*/
icon?: 'x' | 'arrowLeft'
}
```
In this way we can implement better navigation by providing a label.
Examples: 
[#1 ](https://deploy-preview-471--commercelayer-app-elements.netlify.app/?path=/docs/composite-pagelayout--docs)
[#2 ](https://deploy-preview-471--commercelayer-app-elements.netlify.app/?path=/docs/atoms-pageheading--docs#with-nav-go-back)
> Replace `onGoBack` with `navigationButton` in PageHeading

- packages/app-elements/src/ui/forms/InputReadonly.tsx
- packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
Closes #
I've applied a new style for `<InputReadonly>` with new hover effect and support for SkeletonTemplate.
https://deploy-preview-473--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputreadonly--docs
> Update `InputReadonly` style

- packages/app-elements/src/ui/atoms/Grid.tsx
Now it's possible to set items alignment in Grid component
> Add `alignItems` prop in `<Grid>` component

- packages/app-elements/src/ui/forms/InputSelect/AsyncComponent.tsx
Modified `AsyncSelect` to hide `noOptionsMessage` if `initialValues` prop is set as an empty array `[]` and select `search` field is empty.
> Hide `noOptionMessage` for `AsyncSelect` with empty search and empty `initialValues`

- packages/app-elements/src/ui/atoms/Grid.tsx
Added a new `auto` option for `columns` prop of `Grid` component to enable auto flow of grid columns. When the `columns` prop is set to `auto` the TW classname `grid-flow-col` is added to the `Grid` main element.
This setup will behave in having the first column to fill all the available space and the other columns to shrink and adapt to their minimum outer size.
- [] Make sure to add/update documentation regarding your changes.
> Add auto flow cols to grid component

- packages/app-elements/src/helpers/unitsOfWeight.test.ts
- packages/app-elements/src/helpers/unitsOfWeight.ts
- packages/app-elements/src/main.ts
Added `helper` library to introduce and describe units of weight that we share in our apps.
The library will add:
- a `UnitOfWeight` type that is a union of `'gr' | 'oz' | 'lb'`
- a `getUnitsOfWeightForSelect` method to have all units of weight listed as `value` / `label` objects suitable for `InputSelect` options usage
- a `getUnitOfWeightName` method to obtain the name of given unit of weight (eg. `getUnitOfWeightName('gr') = 'Grams'`)
> Add `unitsOfWeight` helper library

- packages/app-elements/src/ui/composite/Dropdown/DropdownItem.test.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/docs/src/stories/composite/Dropdown.stories.tsx
I've added an `href` prop to the dropdown item so it can be rendered also as `<a>` when provided.
https://deploy-preview-487--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#items-different-tags
> Allow `DropdownItem` to be used as anchor

- packages/app-elements/src/ui/atoms/Alert.tsx
Now `Alert` component has a border that matches the variant.
I've also removed the usage of the `Card` inside the `Alert` because it was clashing with css classes that have been recently added to the first one
https://deploy-preview-490--commercelayer-app-elements.netlify.app/?path=/docs/atoms-alert--docs
> Add border variants to Alert

- packages/app-elements/src/ui/atoms/Stack.tsx
- packages/docs/src/stories/atoms/Stack.stories.tsx
To allow multiple Stack(s) to be used, I've added a negative margin of 1px when it is not the first sibling.
In this way when Stack is used as the only sibling (99% of cases, since it is always wrapped in a Spacer) this rule won't be triggered.
And, in case the Stack component is used at the same level of other div, it will just steal an imperceptible 1px on top of the previous element
From this preview https://deploy-preview-494--commercelayer-app-elements.netlify.app/?path=/docs/atoms-stack--docs#multiple-stacks
try to inspect and remove `<div>first sibling<div>` to notice the difference
> Allow to use multiple Stack

- packages/app-elements/src/ui/atoms/Card.tsx
- packages/docs/src/stories/atoms/Card.stories.tsx
I've added a no-gap option (`gap: 'none'`) to the Card, making sure it can still accept a footer.
> Add gap `none` to Card

- packages/app-elements/src/dictionaries/promotions.ts
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
Updated the `disabled` check. Promotions are disabled when `disable_at` attribute is set. Looking to `active` is wrong because `active` indicates if the promotion is active (enabled and not expired).
> Promotion is disabled when `disable_at` is set

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
- packages/docs/src/stories/utility/Date.stories.tsx
`distanceToNow` option on `formatDate` now consider also future dates.
> `distanceToNow` option on `formatDate` now consider also future dates

- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/url.test.ts
- packages/app-elements/src/providers/TokenProvider/url.ts
To prevent the wrong configuration from being set, we now check if `window.location.hostname` matches one of the production subsets.
In that case `commercelayer.io` is used
> Enforce `domain` when production URL is matched

- packages/app-elements/src/providers/TokenProvider/types.ts
We enforced the list of allowed apps in `TokenProvider` by defining a custom union type containing all of our active apps.
> Enforce `TokenProvider` allowed apps

- packages/app-elements/src/helpers/route.test.ts
- packages/app-elements/src/helpers/route.ts
- packages/app-elements/src/main.ts
- packages/docs/src/components/CodeSample.tsx
- packages/docs/src/stories/utility/Route.stories.tsx
I added a new `createRoute` and `createTypedRoute` helpers. Creating routes is now fully type-safe.
```ts
const orderDetailsRoute = createRoute('/orders/:id/')
orderDetailsRoute.path //= '/orders/:id'
orderDetailsRoute.makePath({ id: 'abc' }) //= '/orders/abc'
```
> Add `createRoute` and `createTypedRoute` helpers

- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/types.ts
I've added `dashboard` to the allowed token provider apps.
When it is used, organization data won't be fetched.
> Add dashboard allowed app in token provider

- packages/app-elements/src/dictionaries/orders.ts
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
In case a transaction fails, we now show the event in the timeline with the same message as it was succeded.
Example:  Payment of xxx was authorized, where `authorized` is the past tense of the transaction `type`.
In this PR I've added a check on the `succeeded` attribute to solve this issue.
Result:
> Prevent failed transaction to be displayed as a success message

- packages/app-elements/src/hooks/useOverlay.tsx
I've fixed a behavior where `useOverlay` was not reacting to option changes.
Example:
```ts
// `isFoo` changes dinamically during data fetchiing
const { open } = useOverlay({ queryParam:  isFoo ? 'foo' : 'bar'   })
```
when `isFoo` changes now the `open` method appends the right query param to the URL.
> Make `useOverlay` reactive on `queryParam` changes

- packages/app-elements/src/ui/atoms/Icon/icons.tsx
Fixed `lockSimple` icon key name. I wrongly set the key with capital first letter.
> Fix `lockSimple` icon key name

- packages/app-elements/src/ui/forms/InputSelect/AsyncComponent.tsx
- packages/app-elements/src/ui/forms/InputSelect/HookedInputSelect.tsx
- packages/app-elements/src/ui/forms/InputSelect/InputSelect.test.tsx
- packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
- packages/app-elements/src/ui/forms/InputSelect/SelectComponent.tsx
- packages/app-elements/src/ui/forms/InputSelect/styles.ts
- packages/docs/src/stories/forms/react-hook-form/HookedInputSelect.stories.tsx
- packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
- add `isDisabled` option with the proper css style.
- add the `ref` attribute to access inner functionality from outer component.
- when `isMulti` the menu will stay open after selecting an option (AsyncComponent is still closing the menu).
- add ability to reset the `HookedInputSelect`.
> Few improvements for the `InputSelect` component

- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx
I added an `API` badge when promotion is created from outside the app.
> Add an `API` badge when promotion is created from outside the app

- packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
- packages/app-elements/src/ui/composite/ListDetailsItem.tsx
- packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
- packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx
- packages/app-elements/src/utils/array.ts
- packages/app-elements/src/utils/children.test.tsx
- packages/app-elements/src/utils/children.ts
- packages/docs/src/stories/forms/react-hook-form/HookedInputCheckbox.stories.tsx
- packages/docs/src/stories/forms/ui/InputCheckbox.stories.tsx
I added the ability to show additional `Element`s when the `InputCheckbox` component is checked.
```tsx
<HookedInputCheckbox
name='color_selected'
checkedElement={
<div>
<HookedInputSelect
name='color'
hint={{ text: 'Select your preferred color.' }}
initialValues={[
{ label: 'Red', value: 'red' },
{ label: 'Green', value: 'green' },
{ label: 'Blue', value: 'blue' }
]}
/>
<Spacer top='2'>
<HookedInputCheckbox name='optional_check'>
Optional check
</HookedInputCheckbox>
</Spacer>
</div>
}
>
Color preference
</HookedInputCheckbox>
```
https://github.com/commercelayer/app-elements/assets/1681269/5e2427c3-1748-47fb-9e63-38ac6bdd7a77
https://deploy-preview-533--commercelayer-app-elements.netlify.app/?path=/docs/forms-react-hook-form-hookedinputcheckbox--docs
> Add ability to show additional Elements when checkbox is checked

- packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputCheckbox.stories.tsx
The `HookedInputCheckbox` component will set all Hooked children to undefined when unchecked
https://github.com/commercelayer/app-elements/assets/1681269/0c761f83-917a-4788-861e-0cde4bd2047d
> The `HookedInputCheckbox` component will set all Hooked children to undefined when unchecked

- packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx
- packages/docs/src/stories/forms/ui/InputCheckbox.stories.tsx
`InputCheckbox` can accepts ReactNode as children
> `InputCheckbox` can accepts ReactNode as children

- packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
- packages/docs/src/stories/forms/ui/InputRadioGroup.stories.tsx
In `InputRadioGroup`, it's now possible to pass an optional `className` to each option item.
Example: 
```
options: [
{
value: 'item1',
content: <div>Item #1</div>
},
{
value: 'item2',
className: 'w-full',
content: <div>Item #2</div>
}
]
```
> Add `className` to InputRadioGroup > OptionItem

- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/storage.test.ts
- packages/app-elements/src/providers/TokenProvider/storage.ts
`TokenProvider` saves and loads the token from `localStorage` by inferring the organization slug from the current URL.
With this PR I've extended this behavior and when `organizationSlug` is defined it will be used to build the local storage key, instead of inferring it from the URL
This will only impact self-hosted applications, since in all dashboard `app-*`s we are not using `organizationSlug` and the organization slug will be still inferred from the current URL.
> Aallow TokenProvider to persist token using custom `organizationSlug`

- packages/app-elements/src/helpers/appsNavigation.ts
I set the type of `app` props defined in the `appsNavigation` helper methods to be of type `TokenProviderAllowedApp` instead of SDK's `ResourceTypeLock`. This change should be a refinement of a previous fix made to introduce this new type aimed to take care and control over our active apps.
> Fix type of `app` props in `appsNavigation` helper

- packages/app-elements/src/ui/composite/ListItem.tsx
- packages/docs/src/stories/composite/ListItem.stories.tsx
- Added `variant` prop to `ListItem` component defining `list` (default) and `card` options to give rounded border to the item in case of `card` setup
- Added `disabled` prop to `ListItem` component to enable a different UI for disabled-like usage of a single `ListItem`
> Add `variant` and `disabled` to `ListItem` component

- packages/app-elements/src/ui/atoms/CopyToClipboard.tsx
- packages/app-elements/src/ui/composite/ListDetailsItem.tsx
- packages/docs/src/stories/atoms/CopyToClipboard.stories.tsx
- packages/docs/src/stories/composite/ListDetailsItem.stories.tsx
I've switched the `<ListDetailsItem>` from flex to grid layout.
In this way is easier to handle the fact that children should not break the layout and grow too much, consuming label (left column) spacing.
Example of broken layout:
In this way we do not need to use custom props if children are instructed to use `overlfow: scroll` like `<CopyToClipboard>`  does.
When a long string is passed as children and it's recognized as plain string, it will be trimmed `...` if too long.
This won't happen if the child is a different JSX element.
Layout won't break, but the overflowing rule is demanded to the child (eg: <Text> will take multiple lines since it handle break-words itself)
I've also did a small change to the `CopyToClipboard` component: now if it finds a string that is JSON (eg: json …
> Prevent children of ListDetailsItem to break its layout

- packages/app-elements/src/mocks/handlers.ts
- packages/app-elements/src/ui/resources/useResourceFilters/FilterNav.test.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
We discovered a broken behavior when using a filter item with the `InputResourceGroup` component and more resources were selected as active filters.
Instead of showing the grouped label (es: `Markets · 3`) we were displaying the name for the first resource only (fetching the resource name asynchronously).
This behavior should only happen when we only have 1 resource (relationship) as active filter.
I've now fixed the issue and handled new test cases.
> Grouped button filter is now correctly rendered when multiple relationship-resources are selected as filter value

- packages/app-elements/src/ui/atoms/Container.tsx
- packages/app-elements/src/ui/atoms/Grid.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
- packages/app-elements/tailwind.config.cjs
I've removed the `sm` breakpoint and modified the starting of the `md` one, which now starts at 768px.
The only breakpoints that we handle are:
```
md: '768px',
lg: '992px',
xl: '1200px'
```
> Tune breakpoints and container size

- .github/workflows/test.yaml
- packages/app-elements/src/ui/atoms/Table/Table.tsx
- packages/app-elements/src/ui/atoms/Table/Th.tsx
- packages/docs/src/stories/atoms/Table.stories.tsx
I removed the `overflow-hidden` from the `<Table>` component. This way it can accepts Dropdown components.
https://deploy-preview-551--commercelayer-app-elements.netlify.app/?path=/docs/atoms-table--docs#with-actions
> Remove overflow hidden from table

- packages/app-elements/package.json
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/atoms/Tooltip.test.tsx
- packages/app-elements/src/ui/atoms/Tooltip.tsx
- packages/docs/src/stories/atoms/Tooltip.stories.tsx
- pnpm-lock.yaml
I've added a Tooltip component wrapping the `react-tooltip` library.
Examples and documentation [here](https://deploy-preview-553--commercelayer-app-elements.netlify.app/?path=/docs/atoms-tooltip--docs)
> Add `Tooltip` component

- packages/app-elements/src/ui/atoms/Tooltip.test.tsx
- packages/app-elements/src/ui/atoms/Tooltip.tsx
- packages/docs/src/stories/atoms/Tooltip.stories.tsx
I made `id` optional for the `Tooltip` component.
> `id` is now optional for the `Tooltip` component

- packages/app-elements/src/ui/forms/InputDate/InputDateComponent.css
- packages/app-elements/src/ui/forms/InputDate/InputDateComponent.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputDate.stories.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputDateRange.stories.tsx
- packages/docs/src/stories/forms/ui/InputDate.stories.tsx
- packages/docs/src/stories/forms/ui/InputDateRange.stories.tsx
I added `time` to the InputDate and HookedInputDate components.
https://deploy-preview-556--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputdate--docs#with-time-select
> Add `time` to the InputDate and HookedInputDate components

- packages/app-elements/src/helpers/route.ts
I updated the `GetParams` type.
Before this PR:
```ts
const route = createTypedRoute<{ type: 'A' | 42; enabled?: boolean }>()(
'/orders/:type/:enabled?/'
)
type Params = GetParams<typeof route>
// equivalent to
type Params = {
type: string;
enabled?: string | undefined;
}
```
After this PR:
```ts
const route = createTypedRoute<{ type: 'A' | 42; enabled?: boolean }>()(
'/orders/:type/:enabled?/'
)
type Params = GetParams<typeof route>
// equivalent to
type Params = {
type: 'A' | '42';
enabled?: "false" | "true" | undefined;
}
```
> `GetParams` type better works with `createTypedRoute`

- packages/app-elements/src/ui/atoms/Tabs.tsx
Added a numerical `defaultTab` prop to `Tabs` component to provide a way to define if a particular tab needs to be activated at component mount, instead of the first one available.
> Add `defaultTab` to `Tabs` component

- packages/app-elements/src/main.ts
- packages/app-elements/src/providers/createApp.tsx
`createApp` now generates a cl app init method for the specified app slug.
> Update createApp to include appSlug parameter

- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToSdk.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToFormValues.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToSdk.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/mockedInstructions.ts
- packages/docs/src/stories/resources/useResourceFilters.stories.tsx
When you have an Option instruction with `mode="single"`, the selected value is displayed with the option label.
```js
// instructions
[
{
label: 'Payment Status',
type: 'options',
sdk: {
predicate: 'payment_status_eq'
},
render: {
component: 'inputToggleButton',
props: {
mode: 'single',
options: [
{ value: 'authorized', label: 'Authorized' },
{ value: 'paid', label: 'Paid' },
{ value: 'voided', label: 'Voided' },
{ value: 'refunded', label: 'Refunded' },
{ value: 'free', label: 'Free' },
{ value: 'unpaid', label: 'Unpaid' }
]
}
}
}
]
```
```js
queryString='?payment_status_eq=authorized'
```
Before this change:
After this change:
https://deploy-preview-570--commercelayer-app-elements.netlify.app/?path=/docs/resources-useresourcefilters--docs
> Show the option label when selected value is a string

- packages/app-elements/src/ui/resources/useResourceFilters/FieldOptions.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FieldTextSearch.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersForm.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToSdk.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToSdk.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToUrlQuery.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToFormValues.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToFormValues.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToSdk.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToSdk.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToUrlQuery.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToUrlQuery.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adapters.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adapters.types.ts
- packages/app-elements/src/ui/resources/useResourceFilters/mockedInstructions.ts
- packages/app-elements/src/ui/resources/useResourceFilters/types.ts
- packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
- packages/docs/src/stories/resources/useResourceFilters.stories.tsx
```js
const instructions = [
{
hidden: true,
label: 'Name',
type: 'textSearch',
sdk: {
predicate: 'name_eq'
},
render: {
component: 'input'
}
}
]
```
By default, we strip out all filters that are not part of the `instructions` array.
The option `predicateWhitelist` is used to whitelist a set of predicates that you want to use as filters.
```jsx
useResourceFilters({
instructions,
predicateWhitelist: [
'disabled_at_null',
'starts_at_lteq',
'expires_at_gteq',
'starts_at_gt',
'expires_at_lt'
]
})
```
This way you can redirect to `/list?disabled_at_null=true&expires_at_gteq=2024-02-28T14%3A45%3A10.186Z&starts_at_lteq=2024-02-28T14%3A45%3A10.186Z&viewTitle=Active` without the need of specifying fake or hidden instructions.
> Enhance the `useResourceFilters` hook

- packages/app-elements/src/ui/atoms/CopyToClipboard.tsx
- packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
- packages/docs/src/stories/atoms/SkeletonTemplate.stories.tsx
SkeletonTemplate was not applying the loading style on CopyToClipboard.
I've also changed a `p` tag with `div` since the first can't have a block-level tag as children.
> Add `SkeletonTemplate` support for `CopyToClipboard`

- packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
- packages/docs/src/stories/resources/useResourceFilters.stories.tsx
I removed `filters` from the query prop (`FilteredList` component).
> Filters need to be configured within the `useResourceFilters` options.
> Remove `filters` from the query prop (`FilteredList` component)

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
- packages/app-elements/src/main.ts
- packages/docs/src/components/CodeSample.tsx
- packages/docs/src/stories/utility/Date.stories.tsx
I've moved here the `getLastYearIsoRange` helper we are using in some apps to generate the 1-year date range to be used to get counters from Metrics API.
I've also fixed it to work with leap years.
> Add new date helper `getLastYearIsoRange`

- packages/app-elements/src/ui/forms/InputRadioGroup/HookedInputRadioGroup.tsx
- packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputRadioGroup.stories.tsx
- packages/docs/src/stories/forms/ui/InputRadioGroup.stories.tsx
I enhanced the `InputRadioGroup` component by adding a new `simple` viewMode. It will renders the options as simpler radio inputs
I also added the `checkedElement` prop that will be rendered when the radio is selected:
https://github.com/commercelayer/app-elements/assets/1681269/d982ab61-3c16-4301-912e-2067cdf796f3
https://deploy-preview-579--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputradiogroup--docs#view-mode-simple
> Enhance the `InputRadioGroup` component

- packages/app-elements/src/ui/forms/Input/Input.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInput.stories.tsx
- packages/docs/src/stories/forms/ui/Input.stories.tsx
Closes commercelayer/issues-app#10
I added a `suffix` prop to the `Input` component.
This can be combined with `Icon`s to manage Input actions:
Or it can be simply a text:
https://deploy-preview-581--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-input--docs
> Add 'suffix' prop to the `Input` component

- packages/app-elements/src/dictionaries/promotions.ts
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx
The `ResourceListItem` is rendered as `expired` for promotions that have the `total_usage_count` equal to the `total_usage_limit`.
https://deploy-preview-582--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcelistitem--docs#promotions
> Handle total usage for expiration

- packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
I've exposed the debounceMs prop in FiltersSearchBar so the consumer app can use a custom debounce value.
> Expose `debounceMs` prop to filters search bar

- packages/app-elements/src/ui/composite/ListItem.tsx
- packages/docs/src/stories/atoms/SkeletonTemplate.stories.tsx
- packages/docs/src/stories/composite/ListDetails.stories.tsx
- packages/docs/src/stories/composite/ListItem.stories.tsx
- Replaced variant `card` with `boxed` in `ListItem` component. All involved stories have been updated.
- Added new padding size `6` in `ListItem` component.
- Added a dedicated doc story to describe how to create the new card-like box with button that is now based on `ListItem` component.
> Replace variant `card` with `boxed` in `ListItem` component

- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx
I updated the `hasCoupons` check, that is now checking for the related promotion rule since it is faster.
> `hasCoupons` is now checking for the related promotion rule

- packages/app-elements/src/styles/vendor.css
- packages/app-elements/src/ui/atoms/CopyToClipboard.tsx
- packages/app-elements/src/ui/forms/InputReadonly.tsx
- packages/app-elements/tailwind.config.cjs
- packages/docs/.storybook/preview-head.html
- packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
I've updated the style for the InputReadonly to match the latest design changes and handle case where we want to show the contest as multiple lines of text.
In this case, a string can be passed as children.
Instead of using a `<textarea>` I went for a `<div role='textbox'>`, so we don't need to calculate height dynamically, while keeping everything responsive.
The font family for monospace text is now `Roboto Mono`, so we should update the consumer apps as well
```
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,500;1,500&display=swap" rel="stylesheet" />
```
> InputReadonly to render multi line text content

- packages/app-elements/src/ui/atoms/Card.tsx
- packages/app-elements/src/ui/atoms/StatusIcon.tsx
- packages/app-elements/tailwind.config.cjs
- packages/docs/src/stories/atoms/Card.stories.tsx
- packages/docs/src/stories/examples/Panel.stories.tsx
The `Card` component is rendered as `<a>` when href is set, and is rendered as `<button>` when onClick is set.
https://github.com/commercelayer/app-elements/assets/1681269/18d65583-0c2b-4398-b716-b273b2d6a976
https://deploy-preview-596--commercelayer-app-elements.netlify.app/?path=/docs/atoms-card--docs#button-element
This way the `Card` component can be used as Panel:
https://deploy-preview-596--commercelayer-app-elements.netlify.app/?path=/docs/examples-panel--docs
> `Card` can manage `href` and `onClick`

- packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adapters.ts
I've added the missing logic to handle amounts and currency when using metrics API to fetch a filtered list of orders.
For each `currencyRange` item found in the filters instruction, I build the relative metrics API filter converting the logic, predicate and operators to valid ones.
> Handle amounts and currencies  in sdk-to-metrics filters adapter

- packages/app-elements/src/ui/atoms/Button.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
- packages/docs/src/stories/atoms/Button.stories.tsx
`Button` component is square when contains only one `Icon`.
> `Button` component is square when contains only one `Icon`

- packages/app-elements/src/styles/vendor.css
- packages/app-elements/src/ui/atoms/A.test.tsx
- packages/app-elements/src/ui/atoms/A.tsx
- packages/app-elements/src/ui/atoms/Button.test.tsx
- packages/app-elements/src/ui/atoms/Button.tsx
- packages/app-elements/src/ui/atoms/Icon/icons.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/app-elements/src/ui/internals/InteractiveElement.className.ts
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
- packages/docs/src/stories/atoms/A.stories.tsx
- packages/docs/src/stories/atoms/Button.stories.tsx
- packages/docs/src/stories/composite/List.stories.tsx
The `A` component can render as a button (UI only) and the `Button` component can render as a link (UI only).
Examples for `<A>` are here:
https://deploy-preview-598--commercelayer-app-elements.netlify.app/?path=/docs/atoms-a--docs
Examples for `<Button>` are here:
https://deploy-preview-598--commercelayer-app-elements.netlify.app/?path=/docs/atoms-button--docs
I also added the `mini` size that can be used as mini button when adding new elements:
https://deploy-preview-598--commercelayer-app-elements.netlify.app/?path=/docs/composite-list--docs
When you need to link to an internal or external page, you always have to use the `<A>` component. You can use the `variant` prop to render the link as a button.
When you need to do some action on click, you always have to use the `<Button>` …
> `A` component can render as a button

- packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToUrlQuery.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToUrlQuery.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adapters.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adapters.types.ts
I've added a new adapter `adaptSdkToUrlQuery` in the `useResourceFilters` hook.
> Add resource filters adapter to transform SDK filter object to URL query string

- packages/app-elements/src/ui/composite/CardDialog.tsx
- packages/app-elements/src/ui/composite/ListItem.test.tsx
- packages/app-elements/src/ui/composite/ListItem.tsx
- packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroupItem.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/orders.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
- packages/docs/src/stories/atoms/Card.stories.tsx
- packages/docs/src/stories/atoms/SkeletonTemplate.stories.tsx
- packages/docs/src/stories/composite/CardDialog.stories.tsx
- packages/docs/src/stories/composite/ListDetails.stories.tsx
- packages/docs/src/stories/composite/ListDetailsItem.stories.tsx
- packages/docs/src/stories/composite/ListItem.stories.tsx
- packages/docs/src/stories/examples/ListImports.stories.tsx
- packages/docs/src/stories/examples/ListResources.stories.tsx
- packages/docs/src/stories/examples/ListSkus.stories.tsx
- packages/docs/src/stories/examples/OrderHistory.stories.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputRadioGroup.stories.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputSimpleSelect.stories.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputSwitch.stories.tsx
- packages/docs/src/stories/forms/ui/InputCheckbox.stories.tsx
- packages/docs/src/stories/forms/ui/InputRadioGroup.stories.tsx
- packages/docs/src/stories/forms/ui/InputSimpleSelect.stories.tsx
- packages/docs/src/stories/forms/ui/InputSwitch.stories.tsx
- packages/docs/src/stories/resources/ResourceAddress.stories.tsx
- packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
- packages/docs/src/stories/resources/ResourceList.stories.tsx
- Following recent changes applied to the `Card` component, now also the `ListItem` is losing its `tag` prop to generate the right HTML tag (`div` or `a` or `button`) depending on the optional `href` and `onClick` props.
- The accessibility of the component was improved.
- All the involved stories and test were adapted to meet the new setup.
> Remove `tag` prop from `ListItem` component

- packages/app-elements/src/ui/atoms/Card.tsx
Enforced `button` behavior of `Card` component by adding the `type="button"` HTML attribute to the rendered tag in case the `Card` is expected to behave like a `button`.
> Enforce `button` behavior of `Card` component

- packages/app-elements/src/ui/composite/ListItem.tsx
Enforced HTML `type` attribute of `ListItem` component by checking the `JsxTag` rendered instead of just the `onClick` prop existance.
> Enforce HTML `type` attribute of `ListItem` component

- packages/app-elements/src/ui/composite/SearchBar.tsx
According to updated design the `SearchBar` has now a `white` background when focused.
> Set `white` background to focused `SearchBar`

- packages/app-elements/src/styles/vendor.css
- packages/docs/src/stories/atoms/A.stories.tsx
I added the style for the `a` element to the css. This will simplify the usage of the wouter `Link`.
```tsx
<Link href="https://commercelayer.io">Text</Link>
```
will render as `A`.
https://deploy-preview-606--commercelayer-app-elements.netlify.app/?path=/docs/atoms-a--docs#html-element
> Add the style for the `a` element to the css

- packages/app-elements/src/ui/atoms/Table/Table.test.tsx
- packages/app-elements/src/ui/atoms/Table/Table.tsx
- packages/app-elements/src/ui/atoms/Table/Th.tsx
- packages/docs/src/stories/atoms/Table.stories.tsx
I added the `boxed` variant to the `Table` component.
```tsx
<Table variant='boxed' ... />
```
> Add the `boxed` variant to the `Table` component

- packages/app-elements/src/ui/atoms/Table/Table.tsx
- packages/app-elements/src/ui/atoms/Table/Td.tsx
- packages/docs/.storybook/preview.tsx
- packages/docs/src/stories/atoms/Table.stories.tsx
I added a `bg-white` to the `Td` component.
This way the table renders well on an overlay:
https://deploy-preview-608--commercelayer-app-elements.netlify.app/?path=/docs/atoms-table--docs#variant-boxed
> Add `bg-white` to `Td` component

- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
Enhanced visualization of return line items reason by showing both key and value of reason object rows
> Enhance visualization of return line items reason

- packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
- packages/app-elements/src/main.ts
- packages/app-elements/src/mocks/data/customers.ts
- packages/app-elements/src/ui/atoms/Icon/icons.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/index.tsx
- packages/docs/src/mocks/data/customers.js
- packages/docs/src/mocks/handlers.js
- packages/docs/src/stories/resources/ResourceMetadata.stories.tsx
Closes #
We enhanced the `ResourceMetadata` component by giving the user the opportunity to manage full CRUD operations to text metadata of a given resource.
This enhanced way of managing `metadata` can be enabled by using the new `mode` prop of the component which actually supports `simple` and `advanced` values.
The `simple` mode is the default one and corresponds to the actual usage of the component. The `advanced` mode enables full CRUD as previously described.
Another enhancement is about splitting from the `ResourceMetadata` component the overlay used to show the metadata management form. Now this overlay can be used stand alone thanks to the new `useEditMetadataOverlay` hook.
> Enhance `ResourceMetadata` component

- packages/app-elements/src/helpers/appsNavigation.test.ts
- packages/app-elements/src/helpers/appsNavigation.ts
I've added some new conditions to make `navigateTo` and `backTo` methods be able to work also when apps are loaded within the dashboard.
> Make app (cross) linking work when in dashboard

- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/composite/Toolbar.test.tsx
- packages/app-elements/src/ui/composite/Toolbar.tsx
- packages/app-elements/src/ui/internals/InteractiveElement.className.ts
- packages/docs/src/stories/composite/Toolbar.stories.tsx
Added a new `Toolbar` component that generates a horizontal navigation menu made of `Button`s and `Dropdown`s configured by its props.
Its menu items are configurable by filling the `items` prop and they are rendered as `Button`s as default behavior.
Each menu item could have a grouped hierarchy of `dropdownItems` to define the sub menu shown by clicking it. 
If set, the `dropdownItems` prop will cause the current item to be rendered as a `Dropdown` with a `Button` as clickable label.
Thanks to the grouped behavior of the `dropdownItems` prop a divider line will be automatically rendered between each group.
```TSX
<Toolbar
items={[
{
label: 'Primary',
size: 'small',
onClick: () => {
console.log('Primary')
}
},
{
label: 'Secondary',
icon: 'pulse',
variant: 'secondary',
size: 'small', …
```
> Add Toolbar component

- packages/app-elements/src/styles/vendor.css
- packages/app-elements/src/ui/atoms/Icon/icons.tsx
- packages/app-elements/src/ui/forms/InputReadonly.test.tsx
- packages/app-elements/src/ui/forms/InputReadonly.tsx
- packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
- Added a `secret` prop to hide value from  `InputReadonly` and also show a button to show/hide input value
- add focus outline on the input group level to display outline feedback also when buttons are focused
https://deploy-preview-626--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputreadonly--docs#secret
> Add prop to `InputReadonly` to toggle hidden values

- packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownDivider.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/docs/src/stories/composite/Dropdown.stories.tsx
I've added a `menuWidth` prop to render a wider dropdown menu with a fixed width of 280px.
I've also tuned some spacings in dropdown elements to match the latest design changes.
https://deploy-preview-625--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#menu-width-wide
> Add `wide` variant to `DropdownMenu`

- packages/app-elements/src/ui/atoms/Section.tsx
Section title with size small now renders with a gray-600 color instead of gray-500
> Update section title color

- packages/app-elements/package.json
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.mocks.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressFormFields.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/index.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/useResourceAddressOverlay.tsx
- packages/docs/package.json
- packages/docs/src/mocks/data/addresses.js
- packages/docs/src/mocks/handlers.js
- packages/docs/src/stories/resources/ResourceAddress.stories.tsx
- pnpm-lock.yaml
I exported:
- `useResourceAddressOverlay` hook so that the address overlay can be opened from a dropdown.
- `ResourceAddressFormFields` component can be reused in other forms
https://deploy-preview-637--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourceaddress--docs
> Add `useResourceAddressOverlay` hook and `ResourceAddressFormFields` component can be reused in other forms

- packages/app-elements/src/main.ts
- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/ui/atoms/PageHeading.tsx
- packages/app-elements/src/ui/composite/PageLayout.tsx
- packages/app-elements/src/ui/composite/PageSkeleton.test.tsx
- packages/app-elements/src/ui/composite/PageSkeleton.tsx
- packages/app-elements/src/ui/composite/SearchBar.tsx
- packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
- packages/docs/src/stories/composite/PageSkeleton.stories.tsx
I've removed the old and not-required logic in the existing `PageSkeleton` component and replaced it with a generic loading layout simulating the initial app screen (title, navigation button, search bar, and some list items).
To do so I've also added `withSkeletonTemplate` support to PageHeading, PageLayout, and SearchBar.
Now TokenProvider uses this new `PageSkeleton` component when app is loaded in the dashboard (ignoring the `loadingElement` prop)
https://deploy-preview-641--commercelayer-app-elements.netlify.app/?path=/docs/composite-pageskeleton--docs
> Refactor `PageSkeleton` with a single and generic layout

- packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/app-elements/src/ui/internals/InteractiveElement.className.ts
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
- Managed dedicated `Button` font sizes based on the `size` prop
- Introduced a new temporary `variant` aimed to replace the deprecated dashed `ButtonCard` until the design will find a solution for single relationship selections
> Enforce font sizes of `Button` component

- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Added missing `Spacer`s to `HookedValidationApiError` components used in some resource components
> Add missing `Spacers` to validation api errors

- packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
- packages/app-elements/src/utils/children.test.tsx
- packages/app-elements/src/utils/children.ts
- packages/docs/src/stories/composite/Dropdown.stories.tsx
This won't generate anymore nested buttons
```
<Dropdown
dropdownLabel={
<button>
<Icon name='lifebuoy' size={28} />
</button>
}
...
/>
```
> Allow Dropdown to receive a plain jsx `<button>` tag as label

- packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/app-elements/src/ui/internals/InteractiveElement.className.ts
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Avoided to set button font size with variant `link`
> Avoid setting button font size with variant `link`

- packages/app-elements/src/ui/forms/InputResourceGroup/InputResourceGroup.tsx
Using `queryParam` in  `InputResourceGroup` is causing unwanted component re-rendering when filters are used inside an overlay that already relies on query strings.
Since there is no reason to have the overlay opening with a query param in this component we can safely remove it and keep it simple instead of controlling it with a prop.
> Remove `queryParam` in InputResourceGroup view all overlay

- packages/app-elements/src/providers/ErrorBoundary.tsx
The following approach should inform the user that the file chunk that is trying to load is not available any more on the server. This could mean the app has been updated.
A page refresh will hit the index.html again and the browser will now use the new js assets.
> Handle `ChunkLoadError` in `<ErrorBoundary>` component

- packages/app-elements/src/ui/atoms/PageHeading.tsx
- packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
- packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
- packages/docs/src/stories/composite/PageLayout.stories.tsx
Closes: commercelayer/issues-app#76
Enhanced mobile behaviors of `PageHeading` title by setting the correct text font size for smaller devices and by setting the word break behavior to let it break into multiple lines long titles
> Enhanced mobile behaviors of `PageHeading` title

- packages/app-elements/src/helpers/currencies.test.ts
- packages/app-elements/src/helpers/currencies.ts
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
- packages/app-elements/src/ui/forms/InputSelect/overrides.tsx
- packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
- `InputSelect` now renders an `<Hr>` when a grouped option has no label. Separator won't be rendered for the first group.
- I've added a list of currencies ready to be used as `initialValues` (options) for the `InputSelect` component. The first group of the options is the most used currencies (USD, EUR, GBP) and the second group contains all others currencies.
The generated output is:
```
[
// top currencies
{
options: [
{
label: 'USD',
value: 'USD'
},
{
label: 'EUR',
value: 'EUR'
},
{
label: 'GBP',
value: 'GBP'
}
]
},
// others
{
options: [
{
label: 'AED',
value: 'AED'
},
{
label: 'AFN',
value: 'AFN'
},
...
]
}
]
```
Since the groups have no label, the select component will render a separator
https://deploy-preview-659--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputsel …
> Add currency options with top currencies for `InputSelect`

- packages/app-elements/src/ui/forms/ReactHookForm/HookedValidationApiError.tsx
- packages/app-elements/src/ui/forms/ReactHookForm/setApiFormErrors.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.mocks.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressFormFields.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/useResourceAddressOverlay.tsx
- packages/docs/src/mocks/data/addresses.js
- packages/docs/src/stories/resources/ResourceAddress.stories.tsx
I made a few changes to the ResourceAddress component:
- add the `showNotes` prop to ResourceAddress
- move `line_1` and `line_2` under the same "Address" label
- show error messages when using the input field `name` prefix
- add `showOnlyNameOrCompany` to mutually exclusive show business and non-business fields
https://deploy-preview-660--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourceaddress--docs
> Improve the `ResourceAddress` component

- packages/app-elements/src/dictionaries/shipments.ts
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
- packages/docs/src/stories/resources/ResourceListItem.stories.tsx
I've added a new status for shipments (`delivered`) and updated the icon for the `shipped` status, to match recent design updates.
> Add new `delivered` status to shipments

- packages/app-elements/src/ui/atoms/Icon/icons.tsx
I added the new `usersThree` icon.
> Add new `usersThree` icon

- packages/app-elements/src/ui/forms/InputSelect/HookedInputSelect.tsx
- packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
- packages/app-elements/src/ui/forms/InputSelect/overrides.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedInputSelect.stories.tsx
- packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
I've added a new `menuFooterText` prop to show an optional text at the bottom of the select menu.
The footer text will be shown in both standard and async select, but not while fetching options (async)
https://deploy-preview-666--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputselect--docs#menu-footer-text
I've also exposed the `onSelect` prop in `HookedInputSelect` to access the selected item without affecting the form state.
In the following example (HookedInputSelect -> multi select) when selecting values, an alert will show the full selected item(s)
https://deploy-preview-666--commercelayer-app-elements.netlify.app/?path=/docs/forms-react-hook-form-hookedinputselect--docs#multi-select
> Add optional footer in `InputSelect` menu

- packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
When the form `reset()` method was called, the checkbox was not updated with the proper default value (checked yes/no).
This was due to the fact we should not rely on `defaultValue` when working the with react-hook-form version of the checkbox component, as described here:
https://react-hook-form.com/docs/useform#defaultValues
> The defaultValues prop populates the entire form with default values. It supports both synchronous and asynchronous assignment of default values. While you can set an input's default value using defaultValue or defaultChecked as detailed in the official React documentation, it is recommended to use defaultValues for the entire form.
> Remove `defaultChecked`  in `<HookedInputCheckbox>`

- packages/app-elements/src/ui/forms/InputReadonly.tsx
- packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
I've added some extra right padding to prevent long content overlapping the buttons
Example:
Now:
I've also inverted the show/hide icon when the component is used for secrets since they were set the other way around.
> Prevent content overlapping in `InputReadonly`

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
- packages/docs/src/stories/utility/Date.stories.tsx
I've added a new logic to set a 5-year date range when searching/filtering archived orders with Metrics API.
To do so I've enhanced and renamed  `getLastYearIsoRange` as `getLastYearIsoRange` since now it accepts the `yearsAgo` parameter.
Example: 
```js
makeDateYearsRange({
now: new Date(),
yearsAgo: 5,
showMilliseconds: false
})
```
> Replace `getLastYearIsoRange` with `getLastYearIsoRange`

- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Added quantity information to line item options. It will be shown next to the line option title.
> Add quantity to line item options

- packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
I have exposed the `removeItem` method in `ResourceList` component when used with `children` prop.
We can already use `removeItem` when using the standard `ItemTemplate` prop, but this method was unavailable when the component is used with `children`.
> Expose `removeItem` method in ResourceList children prop

- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
- packages/docs/src/mocks/data/customers.js
linked to commercelayer/issues-app#83
Added support for showing and editing `metadata` values of type `number` and `boolean` in `ResourceMetadata` component.
Values of type `number` will be managed by using an `<HookedInput type="number" ... />`.
Values of type `boolean` will be managed by using an `<HookedInputCheckbox ... />`.
> Show and edit `numbers` and `booleans` in `ResourceMetadata`

- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
- packages/docs/src/mocks/data/customers.js
- Enforced the calculation of wanted input kind by checking the type of the original metadata value instead of the watched value from the form context
- Added `step="any"` property to the `input type="number"` input kind to enable free management of decimal values
- Parsed to float the values with an original value type `number` to fill correctly the `metadata` object sent to the `onSubmit` callback
> Enforce support for `float` values in `ResourceMetadata`

- packages/app-elements/src/ui/forms/InputSelect/CreatableComponent.tsx
- packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
- packages/app-elements/src/ui/forms/InputSelect/utils.test.ts
- packages/app-elements/src/ui/forms/InputSelect/utils.ts
- packages/docs/src/stories/forms/react-hook-form/HookedInputSelect.stories.tsx
- packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
I've added support to input-select creatable: 
https://react-select.com/creatable
When `isCreatable` prop is added to our `InputSelect` component, it will load the `Creatable` component that works as the default select, but also accepts the selection of values not present in the options.
https://deploy-preview-683--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputselect--docs#creatable
https://github.com/commercelayer/app-elements/assets/30926550/f829cf12-e7a3-4258-bb82-3fd309315d84
> Add creatable InputSelect

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/orders.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/returns.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/stockTransfers.tsx
- packages/docs/src/stories/utility/Date.data.tsx
- commercelayer/issues-app#58
- commercelayer/issues-app#140
- commercelayer/issues-app#143
- I added a `showCurrentYear: boolean` to the `formatDate` helper. ([test](https://deploy-preview-685--commercelayer-app-elements.netlify.app/?path=/docs/utility-date--docs))
- I replaced the `·` time separator with `,`. ([test](https://deploy-preview-685--commercelayer-app-elements.netlify.app/?path=/docs/utility-date--docs))
- I added the time in the resource list item. ([test](https://deploy-preview-685--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcelistitem--docs))
- Show the order total amount and status in the list. ([test](https://deploy-preview-685--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcelistitem--docs))
> Show order total amount and status in the list

- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/types.ts
- packages/app-elements/src/providers/createApp.tsx
Now it's possible to pass some data when the app is initialized and have them available within the TokenProvider context.
This means it is possible to do this on app init:
```
window.clApp_orders( node, { ...props, metadata })
```
and access the metadata object later
```
const { settings } = useTokenProvider()
console.log(settings.metedata)
```
> Allow to pass extra info from `createApp.init()` to make them available within `TokenProvider` context

- packages/app-elements/src/ui/composite/Toolbar.tsx
I fixed an unseen behavior of toolbar by setting its icons weight to `regular` instead of `bold`.
> Set toolbar icons weight to regular

- packages/app-elements/src/ui/composite/Toolbar.tsx
Rollbacked a previous change where I wrongly removed the `weight="bold"` prop on the Dropdown menu button icon.
Instead I removed this prop on the buttons that are mapped to be shown in the external slot of the toolbar.
> Fix icon weights in toolbar

- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/getInfoFromJwt.test.ts
- packages/app-elements/src/providers/TokenProvider/getInfoFromJwt.ts
- packages/app-elements/src/providers/TokenProvider/types.ts
- packages/app-elements/src/providers/TokenProvider/validateToken.ts
I've updated TokenProvider component to return `scopes` inside the `settings` object.
Scopes are parsed from the `scope` string found inside the access token (if set).
examples:
```ts
const { settings } = useTokenProvider()
settings.scopes.market?.ids   // array of market ids found in scope
settings.scopes.market?.codes   // array of market codes found in scope
settings.scopes.stock_location?.ids   // array of stock_location ids found in scope
settings.scopes.stock_location?.codes  // array of stock_location codes found in scope
```
> TokenProvider: exposed parsed scopes found in access token

- packages/app-elements/src/ui/forms/InputReadonly.tsx
Closes https://github.com/commercelayer/issues-app/issues/123
I added the proper TW classname (`break-all`) to avoid unwanted behavior of long texts in the multiline usage of `InputReadonly`. The enforcement was also a fix to avoid in general any related unwanted behavior in mobile / small viewports.
This improvement should fix the regex visualization in `sku_lists` app and also many other usages of this kind of input for example during the dashboard onboarding (wrong behavior spotted on mobile devices).
> Manage word break in `InputReadonly`

- packages/app-elements/src/ui/composite/HomePageLayout.tsx
As per design we may need the `toolbar` prop even in the homepage in the near future.
> Add `toolbar` to the `HomePageLayout` component

- packages/app-elements/src/ui/forms/InputSelect/AsyncCreatableComponent.tsx
- packages/app-elements/src/ui/forms/InputSelect/CreatableComponent.tsx
- packages/app-elements/src/ui/forms/InputSelect/GenericAsyncComponent.tsx
- packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
- packages/app-elements/src/ui/forms/InputSelect/SelectComponent.tsx
- packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
I managed the `async-creatable` component from react-select directly inside the `InputSelect`.
https://github.com/user-attachments/assets/89451353-6855-42d7-8556-8f30d93d26f3
https://deploy-preview-716--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputselect--docs#async%20creatable
> Manage the `async-creatable` component from react-select

- packages/app-elements/src/ui/forms/InputDateRange/HookedInputDateRange.tsx
- packages/app-elements/src/ui/forms/InputDateRange/InputDateRange.tsx
- packages/docs/src/stories/forms/ui/InputDateRange.stories.tsx
Now it's possible to set single labels for start and end date of the `InputDateRange` component.
Preview:
https://deploy-preview-721--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputdaterange--docs#with%20individual%20labels
By default you can pass a single (shared) `label` and the component renders as it always rendered
But now it's possible to specify different labels, hints and validation messages:
> Add props to control each single input in date range component

- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
According to design I introduced a new behavior of `ResourceListItem` to automate the padding setup of its `ListItem` based on whether the component is clickable or not.
Clickable items will have both horizontal and vertical padding:
Non clickable items will have just vertical padding:
> Add clickable related padding behavior to `ResourceListItem`

- packages/app-elements/src/ui/composite/ListItem.tsx
Forced overlay behavior to `ListItem` horizontal padding to have it always defined in the idea of `ListItem`s always used inside Cards or Boxed ResourceLists inside `overlay`s.
This enforcement became necessary after the introduction of the new padding behavior in `ResourceListItem` to remove side padding for non clickable items.
This is just a little example about how it would be important to have a more robust ruling about how to deal with lists and list items in their multiple use cases.
> Add overlay behavior to `ListItem` padding

- packages/app-elements/src/main.ts
- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/extras.test.ts
- packages/app-elements/src/providers/TokenProvider/extras.ts
- packages/app-elements/src/providers/TokenProvider/getAccessTokenFromUrl.ts
- packages/app-elements/src/providers/TokenProvider/index.tsx
- packages/app-elements/src/providers/TokenProvider/storage.test.ts
- packages/app-elements/src/providers/TokenProvider/storage.ts
- packages/app-elements/src/providers/TokenProvider/types.ts
Closes commercelayer/issues-app#168
TokenProvider `extras` can now also be passed to the app as an encoded (base64) string in URL parameters.
To do so I've added a `encodeExtras` helper method that can be used to prepare the encoded string
Example:
```ts
encodeExtras({
salesChannels: [
{ name: 'Channel1', client_id: 'client1' },
{ name: 'Channel2', client_id: 'client2' }
],
limits: {
markets: 5,
memberships: 10,
organizations: 3,
skus: 1000
}
})
// will output eyJzYWxlc0NoYW5uZ...uYW1lIjoiQ2hhbm
```
When an `extras` is present, it will adopt a similar persistent behavior as done for the access token: 
- saved in a local storage key (in the format of `sku_lsits:demo-store:extras` )
- removed from URL
When TokenProvider is initialized it will check if extras are present in the following …
> Allow to pass encoded `extras` to TokenProvider from URL query

- packages/app-elements/src/ui/forms/InputSelect/styles.ts
- packages/app-elements/src/ui/forms/InputSpinner/InputSpinner.tsx
- packages/app-elements/src/ui/internals/InputWrapper.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
- packages/app-elements/src/utils/text.test.ts
- packages/app-elements/tailwind.config.cjs
Replaced the old `focus` color to use new `primary` color: `#101111`.
> Replace old `focus` color with new `primary` color

- packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/app-elements/tailwind.config.cjs
I've added the violet color palette and used its default color for dropdown items
> Add violet palette to be used as dropdown item hover background

- packages/app-elements/src/ui/resources/ResourceList/adaptMetricsOrderToCore.test.ts
- packages/app-elements/src/ui/resources/ResourceList/adaptMetricsOrderToCore.ts
Since `order.number` can be a custom string, we don't need to parse it as an integer when converting metrics order into core API order
> Keep order number as string when converting from metrics order shape to core

- packages/app-elements/src/ui/atoms/Table/Th.tsx
- packages/docs/src/stories/atoms/Table.stories.tsx
I fixed a wrong behavior due to the fact we forced `text-left` classname in `<Th>` component.
It was not possible to align the content to the right.
> Allow custom alignments for Th component

- packages/app-elements/src/styles/vendor.css
- packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/app-elements/src/ui/internals/InteractiveElement.className.ts
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
- packages/docs/src/stories/composite/Dropdown.stories.tsx
Anchors have default font-weight (no more bold):
https://deploy-preview-749--commercelayer-app-elements.netlify.app/?path=/docs/atoms-a--docs
Dropdown labels as strings have no underline when not hovered
https://deploy-preview-749--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#dropdown%20label%20as%20string
> Tune anchors style

- packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.test.ts
- packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
- packages/app-elements/src/ui/resources/useResourceFilters/types.ts
Closes commercelayer/issues-app#208
- Allow to use `parseFormValue` also for text search
- Text search in metrics API (aggregated details) now set a default date range of 5 years (was 1)
- focus on FilterSearchBar is always on
> Tweak `useResourceFilters` for metrics api

- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
- packages/docs/src/stories/resources/useResourceFilters.stories.tsx
Closes #
When searching from the resource list, the input gets re-rerendered too often, it loses focus and cursor moves to the end, especially when text is deleted.
https://github.com/user-attachments/assets/55e0d6e6-4359-4ca4-a44b-8997206d4747
This PR fixes this behaviour by minimizing the re-rendering.
https://github.com/user-attachments/assets/23361e18-0ebf-445d-853e-ce20650a0001
**Breaking change:**
`queryString` does not exist anymore in `<SearchWithNav>` since now it's handled internally
> Prevent FiltersSearchBar useless rerendering

- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
- packages/docs/src/stories/resources/useResourceFilters.stories.tsx
This restore the `queryString` prop in FilterSearchBar wrongly removed in #755
> restore `queryString` prop in FilterSearchBar

- packages/app-elements/package.json
- packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
- packages/app-elements/src/ui/resources/ResourceList/infiniteFetcher.ts
- pnpm-lock.yaml
Improved typing of `query` prop of `ResourceList` component to follow given resource `type`.
This improvement enable the `query` prop to set for example resource dedicated sort fields.
> Improve type of `query` prop of `ResourceList` component

- packages/app-elements/src/ui/forms/Input/Input.tsx
Increased right padding of input field in `Input` component if `suffix` prop is set.
This was made to prevent any kind of overlap or hidden/unreadable text below the suffix.
> Improve `Input` behaviors with `suffix` prop set

- packages/app-elements/src/hooks/useEditTagsOverlay.tsx
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/atoms/Tag.tsx
- packages/app-elements/src/ui/resources/ResourceTags.tsx
I refactorized the `ResourceTags` component to meet new design requirements. The single `Tag` atom was updated too.
I also detached the tags editing overlay to follow the same approach used for `Metadata` to let the overlay to be used from outside the `ResourceTags` component (for example to have a `Edit tags` menu item in resource context menu)
> Refactor `ResourceTags` component

- packages/app-elements/src/ui/resources/ResourceTags.tsx
Fixed `ResourceTags` edit ability check
> Fix `ResourceTags` edit ability check

- packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
Enforced empty check of `reference` related fields in `ResourceDetails` components
> Enforce empty check of `ResourceDetails` components

- packages/app-elements/src/ui/atoms/Table/Table.tsx
- packages/app-elements/src/ui/atoms/Table/Td.tsx
- packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
- packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
- packages/docs/src/mocks/data/orders.js
- packages/docs/src/stories/resources/ResourceList.stories.tsx
[Preview](https://deploy-preview-777--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcelist--docs#as%20table%20variant) 
I have added a new `ResourceList` variant to render the fetched content as a table.
When setting `variant='table'` a new `headings` prop is required to define the table heading columns.
Example
```tsx
<ResourceList
title='Orders'
type='orders'
variant='table'
headings={[
{ label: 'NUMBER' },
{ label: 'MARKET' },
{ label: 'TOTAL', align: 'right' }
]}
actionButton={
<Button variant='secondary' size='mini' alignItems='center'>
<Icon name='plus' /> Order
</Button>
}
ItemTemplate={({ resource = mockedOrder, isLoading }) => {
return (
<Tr>
<Td isLoading={isLoading}>#{resource.number}</Td>
<Td isLoading={isLoading}>{resource.market?.name}</Td>
<Td …
```
> Add variant `table` in `ResourceList`

- packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/index.tsx
- packages/docs/src/stories/resources/ResourceMetadata.stories.tsx
- Removed unused `mode` prop in `ResourceMetadata` component and nested components
- Finally fixed `ResourceMetadata` edit overlay by adopting the `useCallback` hook to load it
- Refined the `ResourceMetadata` values list by adopting `ListDetailsItem` component instead of `ListItem`
> Cleanup props of `ResourceMetadata` component

- packages/app-elements/src/dictionaries/returns.ts
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
I managed the `refunded` return status.
https://deploy-preview-796--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcelistitem--docs#returns
> Manage `refunded` return status

- packages/app-elements/src/ui/resources/useResourceList/useResourceList.tsx
I've update the type definition for useResourceList since `emptyState` prop could be any ReactNode (including null or string)
> Adjust type for `emptyState` prop in `useResourceList` to accept any ReactNode

- packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
- packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetailsForm.tsx
- packages/app-elements/src/ui/resources/ResourceDetails/useEditDetailsOverlay.tsx
- packages/docs/src/stories/resources/ResourceDetails.stories.tsx
Added `onUpdated` prop to `ResourceDetails` component to be able to manage any kind of callback in consumer apps that should happen once the internal patch of the resource managed by the component is completed.
An example usage should be this one:
```
<ResourceDetails
resource={resourceData}
onUpdated={async () => {
void mutateResource()
}}
/>
```
> Make `ResourceDetails` editable

- packages/app-elements/src/ui/resources/useResourceList/useResourceList.tsx
I've fixed a regression with the default title size in `useResourceList` hook (former `useResourceList`).
Lists of resources by default have a small title, but table and boxed variants have a normal title size unless manually specified.
> Restore original behavior of title size in resource list

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
Closes commercelayer/issues-app/issues/246
Replaced time format of `formatDate` helper to show 0-23 hours instead of 1-24 according to `date-fns` documentation:
https://date-fns.org/v4.1.0/docs/format
> Enhance `formatDate` time formatting

- .gitignore
- packages/app-elements/package.json
- packages/app-elements/src/main.ts
- packages/app-elements/src/mocks/setup.ts
- packages/app-elements/src/ui/forms/CodeEditor/CodeEditor.tsx
- packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx
- packages/app-elements/src/ui/forms/CodeEditor/HookedCodeEditor.tsx
- packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.test.ts
- packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.ts
- packages/app-elements/src/ui/forms/CodeEditor/index.tsx
- packages/docs/src/stories/forms/react-hook-form/HookedCodeEditor.stories.tsx
- packages/docs/src/stories/forms/ui/CodeEditor.stories.tsx
- pnpm-lock.yaml
I created the new `CodeEditor` component.
You can test the autocompletion for promotion rules (json-schema) in the link below:
https://deploy-preview-762--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-codeeditor--docs#promotion%20rules
The `field` and `selector` attributes use core resources information.
> Add `CodeEditor` component

- packages/app-elements/src/ui/internals/InputWrapper.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
I've removed an not required css classname to mitigate a regression with latest (130.0.6723.59 - at the time of writing) chromium engine
https://issues.chromium.org/issues/374034249
> Clean up unwanted css class in InputWrapper

- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/resources/ResourcePaymentMethod.mocks.tsx
- packages/app-elements/src/ui/resources/ResourcePaymentMethod.test.tsx
- packages/app-elements/src/ui/resources/ResourcePaymentMethod.tsx
- packages/docs/src/stories/resources/ResourcePaymentMethod.stories.tsx
Closes commercelayer/issues-app#154
I've added a new component `ResourcePaymentMethod` that accept an order or a customer payment source and render the payment method with the relative icon.
If the payment source contains the `payment_response` object, the component will show a "show more" button to view more info
https://deploy-preview-809--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcepaymentmethod--docs
> Add `ResourcePaymentMethod` component

- packages/app-elements/src/ui/forms/MarketWithCurrencySelector/HookedMarketWithCurrencySelector.tsx
Market search in `<MarketWithCurrencySelector>` was failing due to a broken filter object composition.
> Correct broken query in `MarketWithCurrencySelector`

- packages/app-elements/src/ui/resources/ResourcePaymentMethod.test.tsx
- packages/app-elements/src/ui/resources/ResourcePaymentMethod.tsx
- packages/docs/src/stories/resources/ResourcePaymentMethod.stories.tsx
I've added some props to better control UI for the new `ResourcePaymentMethod` since it the show more button should not be always visible when `payment_response` is present.
> Add new props to better control UI in `ResourcePaymentMethod`

- packages/app-elements/src/hooks/useOverlay.tsx
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressFormFields.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/index.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/useResourceAddressOverlay.tsx
- packages/docs/src/stories/resources/ResourceAddress.stories.tsx
This PR adds/edits a few things to the `ResourceAddress` component:
- I added a new prop called `requiresBillingInfo`. When `true`, it forces `billing_info` as a required field.
- I removed unnecessary re-renders.
- **Breaking Change** - I renamed the prop `resource` to `address`.
> Add `requiresBillingInfo` prop to the ResourceAddress component

- packages/app-elements/package.json
- packages/app-elements/src/providers/TokenProvider/TokenProvider.test.tsx
- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/getOrganization.ts
- packages/app-elements/src/providers/TokenProvider/url.test.ts
- packages/app-elements/src/providers/TokenProvider/url.ts
- packages/app-elements/src/providers/TokenProvider/validateToken.test.ts
- packages/app-elements/src/providers/TokenProvider/validateToken.ts
- packages/app-elements/src/providers/createApp.tsx
- pnpm-lock.yaml
Closes commercelayer/issues-app#182
TokenProvider does not accept anymore `domain` prop.
Base API endpoint will be derived now from `iss` property present in access token.
> Remove `domain` prop in TokenProvider

- packages/app-elements/src/ui/atoms/Text.test.tsx
- packages/app-elements/src/ui/atoms/Text.tsx
This pull request updates the class names for the 'success' variant in the `Text` component and its associated test to ensure consistency with the design system.
Changes to class names:
* [`packages/app-elements/src/ui/atoms/Text.tsx`](diffhunk://#diff-4f5cdc7d7824d84d608c60bde39d231198635d691bcfb6583cd47418d6ac9d64L40-R40): Updated the class name for the 'success' variant from `text-green` to `text-green-600`.
Updates to tests:
* [`packages/app-elements/src/ui/atoms/Text.test.tsx`](diffhunk://#diff-487c3149188a57a5e655e7314d931e16762fee8a8940313829f405969204a4ccL52-R52): Modified the test for the 'success' variant to check for the updated class name `text-green-600`.
> Update green color for text success

- packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
- packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
- packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/docs/src/stories/composite/Dropdown.stories.tsx
I have added a new prop `info` to `DropdownItem` to show a right content as grey text.
[preview 1](https://deploy-preview-823--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#with%20info) 
I've also set the max height to dropdown menu to show a scrollbar when there are too many items
[preview 2](https://deploy-preview-823--commercelayer-app-elements.netlify.app/?path=/docs/composite-dropdown--docs#with%20scrollbar)
> Add `info` prop in `DropdownItem`

- packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.test.tsx
- packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.tsx
I fixed the dropdown visibility when empty.
> Dropdown when empty is no more visible

- packages/app-elements/src/ui/atoms/PageHeading/PageHeading.test.tsx
- packages/app-elements/src/ui/atoms/PageHeading/PageHeading.tsx
- packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
- packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
- packages/docs/src/stories/atoms/PageHeading.stories.tsx
- packages/docs/src/stories/composite/PageLayout.stories.tsx
Closes commercelayer/issues-app#254
The toolbar when navigationButton is not defined displays beside the title.
https://deploy-preview-834--commercelayer-app-elements.netlify.app/?path=/docs/atoms-pageheading--docs
https://deploy-preview-834--commercelayer-app-elements.netlify.app/?path=/docs/composite-pagelayout--docs#without%20navigation%20button
> Toolbar when navigationButton is not defined displays beside the title

- packages/app-elements/src/ui/atoms/PageHeading/PageHeading.test.tsx
- packages/app-elements/src/ui/atoms/PageHeading/PageHeading.tsx
- packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
- packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
Vertical padding in PageHeading for mobile viewport is too high.
We decided to make it smaller
**Was:**
(too much space between topbar and <- back button)
----
**Now:**
> Set responsive paddings on `PageHeading`

- .github/workflows/pkg-pr-new.yaml
- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/providers/createApp.tsx
This pull request introduces several changes to enhance the flexibility and functionality of the `TokenProvider` component. The most important changes include adding support for custom storage methods in the `TokenProvider`, and modifying the `ClAppProps` interface to accept almost all `TokenProvider` props.
* Added an optional `storage` property to the `TokenProviderProps` interface, allowing custom methods for persisting and retrieving access tokens and extra data.
* Updated the `TokenProvider` component to use the custom storage methods if provided, or fallback to the internal methods otherwise. [[1]](diffhunk://#diff-b99b20a022b0c3e3a296d0c1ec8def0c985ae59aaf5626796c61a0824fb216f3R146) [[2]](diffhunk://#diff-b99b20a022b0c3e3a296d0c1ec8def0c985ae59aaf5626796c61a0824fb216f3L142-R172) …
> Add storage methods in `TokenProvider`

- packages/app-elements/package.json
- packages/app-elements/tsconfig.json
- packages/app-elements/tsconfig.node.json
- packages/app-elements/vite.config.js
- pnpm-lock.yaml
- Rename `vite.config.ts` as `vite.config.js` to better handle linting and build process
- Remove unused package  (`@types/testing-library__jest-dom)
- Enforce css file name on vite build config to match previous default name
> Set fixed css filename in bundled output

- packages/app-elements/src/ui/forms/InputSelect/HookedInputSelect.tsx
- packages/docs/src/mocks/data/tags.js
- packages/docs/src/stories/forms/react-hook-form/HookedInputSelect.stories.tsx
I fixed the issue on the multi-async-select where defaultValues didn't apply.
> multi-async-select works well with `defaultValues`

- packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx
- packages/docs/src/stories/forms/ui/CodeEditor.stories.tsx
I added an `organization-config` value to the `jsonSchema` property for the `CodeEditor` component.
This setting will help you in writing a proper valid JSON for the `organization.config` attribute.
https://github.com/user-attachments/assets/8d2962a5-156b-401c-80ce-a1e99f942762
> Add `organization-config` schema to the CodeEditor component

- packages/app-elements/src/ui/resources/useResourceFilters/FieldTimeRange.tsx
In `useResourceFilters` hook, when a custom date range overlay is open the url query string changes and a custom parameter is added.
This is causing the remounting of the entire form component that is built to react to changes in query string.
In this PR I have removed the `queryParam` option to prevent unwanted re-mounting of the filters form component, when the custom date range overlay is open
> Preserve `useResourceFilters` form state when opening date range overlay

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
Closes commercelayer/issues-app#271
This pull request includes changes to the `formatDateRange` function and its associated tests to handle different timezones correctly. The most important changes involve updating the `formatDateRange` function to adjust for timezone offsets and adding new test cases to ensure the function works as expected with various timezones.
> Handle `formatDateRange` with timezone

- packages/app-elements/src/ui/atoms/Tooltip.tsx
According to a related design request I enforce Tooltip UI by setting the wanted max width classname to wrap text in case of long content.
> Enforce Tooltip UI with max width

- packages/app-elements/src/helpers/useAppLinking.ts
I moved the persistency of the "go back" item in session storage.
This will allow to:
- keep separated history between different tabs
- do not pollute cookies with unwanted data
> Replace cookie usage with session storage for app cross-linking

- packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx
Code editor now refers to `domain` found in token provider to download the required schema.
> Infer CodeEditor schema domain from token

- packages/app-elements/src/providers/GTMProvider.test.tsx
- packages/app-elements/src/providers/GTMProvider.tsx
I remove the check `isValidGtmId` when initializing the GTMProvider since the scenario is already managed by GTM out-of-the-box.
> Remove `isValidGtmId` method from the `GTMProvider`

- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
- packages/docs/src/mocks/data/customers.js
Closes commercelayer/issues-app/issues/274
Fixed long text visualization in `ResourceMetadata` component by replacing `flex` with `grid` layout for showing columns.
> Fix long text visualization in `ResourceMetadata` component

- packages/app-elements/src/helpers/tracking.ts
- packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
Closes commercelayer/issues-app#300
I have relaxed the `rateSchema` and set `delivery_date`, `est_delivery_days` and `formatted_delivery_date` optional since they won't be always available from easy post
> Relax shipping rates schema

- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.mocks.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
Closes commercelayer/issues-app/issues/302
Enhanced `ResourceAddress` visualization to show both `first_name` + `last_name` and/or `company` attributes same as they are shown in the edit/create form since the two groups could be filled together and this particular case is not reflected in the `full_name` attribute of the address.
> Enhance `ResourceAddress` visualization

- packages/app-elements/package.json
- packages/app-elements/src/ui/resources/ResourcePaymentMethod.tsx
Closes commercelayer/issues-app/issues/277
Added empty check on `payment_response` in `ResourcePaymentMethod` component to avoid the show of empty Payment response detail.
> Avoid empty  `payment_response` visualization

- packages/app-elements/src/ui/atoms/Icon/icons.tsx
I added the `diamonds-four` and `trend-up` icons.
> Add `diamonds-four` and `trend-up` icons

- packages/app-elements/src/styles/vendor.css
- packages/app-elements/src/ui/internals/InteractiveElement.className.ts
- packages/docs/src/stories/atoms/Button.stories.tsx
I added an `input` variant to the `<Button>` component.
https://deploy-preview-872--commercelayer-app-elements.netlify.app/?path=/docs/atoms-button--docs#input
> Add an 'input' variant to the Button component

- packages/app-elements/package.json
- packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
- packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/orders.tsx
- pnpm-lock.yaml
I've added support for apps organization config exposing `shouldRender` method in TokenProvider context.
I've also added a login in `ResourceListItem` of type `orders` to hide the name of the market if is the only market available in the organization.
> Add `shouldRender` method in `<TokenProvider>`

- packages/app-elements/src/helpers/date.test.ts
- packages/app-elements/src/helpers/date.ts
- packages/app-elements/src/ui/forms/InputDateRange/InputDateRange.tsx
Closes commercelayer/issues-app#324
In `formatDateRange` we were wrongly modified range using timezone offset.
Instead we can safely rely on `formatInTimeZone` imported form `date-fns-tz`.
Also test cases where not correctly defined. New cases added should better cover proper usage.
I've also updated the `InputDateRange` component that now sets as `to` date the end of the day, unless `showTimeSelect` is active.
> Avoid wrong timezone conversions in `formatDateRange` helper

- packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
Closes commercelayer/issues-app/issues/327
Restored previous shipment `ResourceListItem` behavior to show stock location instead of shipping method.
> Show stock location in shipment list item

- packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
When `stock_location` is not available in `ResourceListItem` for `shipments`,  it will display the shipping method name.
> Set `additionalInfos` in ResourceListItem > shipments to work either with stock location or shipping method

- packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.test.tsx
- packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.tsx
- packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
- packages/app-elements/src/ui/composite/Toolbar.tsx
- packages/docs/src/stories/composite/PageLayout.stories.tsx
According to design team I updated the requirements of page heading generated toolbar:
- The first primary button defined in `buttons` attribute of `toolbar` prop will always be visible (desktop + mobile). Now it is visible only on desktop viewport.
- The dropdown wrapper should disappear along with the inner dropdown if it is not visible to avoid the wrapper to be considered as part of the flex elements and the given gap.
While updating the implementation according to the requirement part of the code was improved in terms of documentation and readability.
> Update requirements of page heading generated toolbar

- packages/app-elements/src/ui/atoms/Spacer.tsx
Enforced `Spacer` component to avoid the unwanted behavior of an empty element with spaces if `children` prop is `null`.
> Enforce `Spacer` component

- packages/app-elements/src/providers/I18NProvider.tsx
Switched off default debug of i18n and enabled the `I18NProvider` to set the `debug` thanks to an additional prop.
> Switch off default debug of i18n

- packages/app-elements/src/ui/resources/useResourceFilters/FieldOptions.tsx
This pull request includes a change to the `FieldOptions` function in `FieldOptions.tsx` to improve how the total count of options is computed by excluding hidden options.
Changes in `FieldOptions` function:
* [`packages/app-elements/src/ui/resources/useResourceFilters/FieldOptions.tsx`](diffhunk://#diff-e569f1bc1b78544f8379bc987089ba58b5e41123a5e543c36ca09cb6a6b01a06L24-R26): Modified the `totalCount` calculation to filter out options where `isHidden` is `true`.
> Ignore hidden filters options in field label count

- packages/app-elements/src/ui/resources/ResourceTags.tsx
Closes commercelayer/issues-app/issues/321
Increased the `pageSize` of resource tags listed in `ResourceTags` component. This changes was made since some organizations are able to assign more then 10 (the actual default requests pageSize) tags to the resources.
> Increase pageSize of resource tags list

- packages/app-elements/src/dictionaries/orders.ts
I handled the order status `approved:free:in_progress`.
> Handle order with status `approved:free:in_progress`

- packages/app-elements/src/ui/forms/InputDate/InputDateComponent.css
Closes commercelayer/issues-app#348
I've set same z-index value used in dropdown to date-picker.
This prevents other elements like code editor to overlap the picker menu.
> Prevent date picker to be hidden by other elements

- packages/app-elements/src/ui/atoms/PageHeading/PageHeading.tsx
- packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
- packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
Enforce word break in `PageHeading` title to avoid the overlap of long titles.
> Enforce word break in `PageHeading` title

- packages/app-elements/src/ui/atoms/Avatar.tsx
- packages/docs/src/stories/atoms/Avatar.stories.tsx
Avoid showing broken images when notFound.
https://deploy-preview-926--commercelayer-app-elements.netlify.app/?path=/docs/atoms-avatar--docs
> Avoid showing broken images when notFound (`Avatar`)

- packages/app-elements/package.json
- packages/app-elements/src/helpers/date.ts
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/forms/InputDate/InputDateComponent.tsx
- packages/app-elements/src/ui/forms/InputDateRange/InputDateRange.tsx
- pnpm-lock.yaml
Added support for customizable timezone in `InputDate` and `InputDateRange` components via dedicated `timezone` prop.
At the moment the `InputDate` components are only supporting the user's browser timezone according to the default behavior of the `react-datepicker` package which does not provide an out of the box way to configure a `timezone`.
Many issues were opened inside the project's repository but none of them was considered to provide an official solution.
This feature aims to rework the standard behavior of the `react-datepicker` to support a customizable `timezone` used to render the selected date time and update as well the selected value.
> Add support for timezone in `InputDate` and `InputDateRange` components

- packages/app-elements/src/locales/en.ts
Fixed a copy error in a translation of returns timeline string.
> Fix translation of returns timeline string

- packages/app-elements/src/ui/forms/InputDateRange/InputDateRange.test.tsx
Enforced tests by adding a `waitFor` directive to await correctly the render of `InputDateRange` lazy component after some tests related to it started failing randomly.
> Enforce tests for lazy component

- packages/app-elements/src/ui/composite/PageLayout.tsx
It's now possible to set the sticky footer when `PageLayout` works as overlay using `overlayFooter` prop.
> Enable `overlayFooter` prop in `PageLayout` when working as overlay

- packages/app-elements/src/helpers/transactions.test.ts
- packages/app-elements/src/helpers/transactions.ts
- packages/app-elements/src/locales/en.ts
- packages/app-elements/src/locales/it.ts
- packages/app-elements/src/main.ts
- packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Add an helper to identify async captures.
I've also removed the order timeline event in case the capture is async.
It will be shown as succeeded or failed once the async job is completed.
> Add helper to identify async captures and remove them from timeline

- packages/app-elements/src/ui/composite/Address.tsx
- packages/app-elements/src/ui/internals/useCountryList.ts
- packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressFormFields.tsx
Closes commercelayer/issues-app#335
In the Address and ResourceAddress component, instead of showing country code, we now display the full country name.
To do so I've moved the get countries api call from the address edit form, into a shared hook to be used also in the address display component.
[Storybook preview](https://deploy-preview-942--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourceaddress--docs)
> Show full country name in Address component

- packages/app-elements/src/dictionaries/promotions.ts
- packages/app-elements/src/locales/en.ts
- packages/app-elements/src/locales/it.ts
- packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
I enhanced promotion display status with priority and exclusivity labels
https://deploy-preview-959--commercelayer-app-elements.netlify.app/?path=/docs/resources-resourcelistitem--docs#promotions
> Enhance promotion display status with priority and exclusivity labels

- packages/app-elements/src/ui/atoms/Icon/Icon.tsx
- packages/app-elements/src/ui/atoms/Icon/icons.tsx
I added the `star` icon and the `fill` weight.
https://deploy-preview-962--commercelayer-app-elements.netlify.app/?path=/docs/atoms-icon--docs
> Add `star` icon with `fill` weight

- packages/app-elements/src/ui/atoms/Tooltip.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
When "Remove" button is disabled it was not aligned with the "Swap" button.
This PR fixes this.
Was:
Now:
> Fix buttons alignment in `ResouceLineItems`

- packages/app-elements/src/hooks/useViewJsonOverlay.tsx
- packages/app-elements/src/locales/en.ts
- packages/app-elements/src/locales/it.ts
- packages/app-elements/src/main.ts
- packages/app-elements/src/styles/global.css
- packages/app-elements/src/ui/internals/Overlay.tsx
- packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
- packages/docs/src/stories/hooks/useOverlay.stories.tsx
Related to commercelayer/issues-app#273
> Show full metadata JSON

- packages/app-elements/src/styles/global.css
Closes commercelayer/issues-app#433
I've fixed a wrong style being applied to input inside the react-select component (on focus-visibile)
[Preview](https://deploy-preview-979--commercelayer-app-elements.netlify.app/?path=/docs/forms-ui-inputselect--docs)
> Remove double outline in InputSelect component on focus-visible

- packages/app-elements/src/ui/atoms/Tag.tsx
- packages/docs/src/stories/atoms/Tag.stories.tsx
- packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
Closes commercelayer/issues-app#440
I added the `overflow-wrap: anywhere` property to prevent text from overflowing its line box to the `Tag` component.
https://deploy-preview-985--commercelayer-app-elements.netlify.app/?path=/docs/atoms-tag--docs#wrap-anywhere
> Update `Tag` style to prevent text from overflowing its line box

- packages/app-elements/src/ui/atoms/Avatar.test.tsx
- packages/app-elements/src/ui/atoms/Avatar.tsx
- packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
- packages/app-elements/src/ui/resources/ResourceListItem/transformers/skuListItem.tsx
closes commercelayer/issues-app#16
I improved the types for the `<Avatar>` src prop. Now you're no longer forced to use **as &#96;https://${string}&#96;** when the incoming url is defined as `string | null | undefined`.
> Improve the types for the `<Avatar>` src prop
